/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current account and app configuration */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSettings"];
        put: operations["updateSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gateway/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aliases known to the gateway */
        get: operations["listGatewayModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        get: operations["getProject"];
        put: operations["updateProject"];
        post?: never;
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        get: operations["listChapters"];
        put?: never;
        post: operations["createChapter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/bible": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        get: operations["listBibleEntries"];
        put?: never;
        post: operations["createBibleEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bible-entries/{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entryId: components["parameters"]["entryId"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["updateBibleEntry"];
        post?: never;
        delete: operations["deleteBibleEntry"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{chapterId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        get: operations["getChapter"];
        /** Rename or move a chapter */
        put: operations["updateChapter"];
        post?: never;
        delete: operations["deleteChapter"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{chapterId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Save the chapter text; may create an autosave snapshot */
        put: operations["saveChapterContent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{chapterId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        get: operations["listChapterVersions"];
        put?: never;
        /** Take a labelled snapshot by hand */
        post: operations["createChapterSnapshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{chapterId}/versions/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
                versionId: components["parameters"]["versionId"];
            };
            cookie?: never;
        };
        get: operations["getChapterVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{chapterId}/versions/{versionId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
                versionId: components["parameters"]["versionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Snapshot the current text, then replace it with the version */
        post: operations["restoreChapterVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{chapterId}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        /** Runs of a chapter, newest first */
        get: operations["listChapterRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop a running run; a finished run is returned unchanged */
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        /**
         * Follow a run as Server-Sent Events
         * @description Replays the stored events with a sequence number above `after` (or
         *     the `Last-Event-ID` header), then follows the run live. Each event has
         *     `id` set to its sequence number, `event` set to its type and `data`
         *     holding the JSON payload. The stream ends after `run.finished`, or
         *     after an `end` event when the run was already over; the browser then
         *     closes the EventSource instead of reconnecting.
         */
        get: operations["streamRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/writers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWriters"];
        put?: never;
        post: operations["createWriter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/writers/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a short sample request through the gateway */
        post: operations["testWriter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/writers/{writerId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                writerId: components["parameters"]["writerId"];
            };
            cookie?: never;
        };
        get: operations["getWriter"];
        put: operations["updateWriter"];
        post?: never;
        delete: operations["deleteWriter"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/writers/{writerId}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                writerId: components["parameters"]["writerId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["duplicateWriter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: {
                code: string;
                message: string;
            };
        };
        User: {
            /** Format: uuid */
            id: string;
            username: string;
            display_name: string;
            /** @enum {string} */
            role: "admin" | "author";
            /** Format: date-time */
            created_at: string;
        };
        Me: {
            user: components["schemas"]["User"];
            app_name: string;
            default_model_alias: string;
            alias_prefix: string;
        };
        Settings: {
            scene_token_limit: number;
            autosave_snapshot_minutes: number;
        };
        SettingsInput: {
            scene_token_limit: number;
            autosave_snapshot_minutes: number;
        };
        GatewayModels: {
            alias_prefix: string;
            /** @description Models whose id starts with the alias prefix */
            aliases: string[];
            all_models: string[];
        };
        Project: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ProjectSummary: components["schemas"]["Project"] & {
            chapter_count: number;
        };
        ProjectInput: {
            name: string;
            description?: string;
        };
        ChapterSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            title: string;
            position: number;
            content_hash: string;
            content_length: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Chapter: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            title: string;
            position: number;
            content_md: string;
            content_hash: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ChapterCreateInput: {
            title: string;
            content_md?: string;
        };
        ChapterMetaInput: {
            title: string;
            position?: number;
        };
        ChapterContentInput: {
            content_md: string;
            /** @description Hash the client last loaded; when set and stale the save is refused with 409 */
            base_hash?: string;
        };
        ChapterSaveResult: {
            chapter: components["schemas"]["Chapter"];
            snapshot_created: boolean;
        };
        ChapterVersionSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            chapter_id: string;
            /** @enum {string} */
            kind: "autosave" | "manual" | "pre_revision" | "pre_restore";
            label: string;
            content_hash: string;
            content_length: number;
            /** Format: date-time */
            created_at: string;
        };
        ChapterVersion: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            chapter_id: string;
            /** @enum {string} */
            kind: "autosave" | "manual" | "pre_revision" | "pre_restore";
            label: string;
            content_md: string;
            content_hash: string;
            /** Format: date-time */
            created_at: string;
        };
        SnapshotInput: {
            label?: string;
        };
        /** @enum {string} */
        BibleSection: "premise" | "character" | "setting" | "timeline" | "style" | "chapter_summary";
        BibleEntry: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            section: components["schemas"]["BibleSection"];
            title: string;
            fields: {
                [key: string]: string;
            };
            /** Format: uuid */
            chapter_id?: string;
            position: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        BibleEntryInput: {
            section: components["schemas"]["BibleSection"];
            title: string;
            fields: {
                [key: string]: string;
            };
            /** Format: uuid */
            chapter_id?: string;
            position?: number;
        };
        /** @enum {string} */
        WriterRole: "critic" | "co-writer";
        Writer: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            model_alias: string;
            system_prompt: string;
            roles: components["schemas"]["WriterRole"][];
            enabled: boolean;
            /** Format: double */
            temperature: number;
            is_system: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        WriterInput: {
            name: string;
            /** @description Defaults to "{APP_NAME}-{slug}" when empty on create */
            model_alias?: string;
            system_prompt: string;
            roles: components["schemas"]["WriterRole"][];
            enabled: boolean;
            /** Format: double */
            temperature: number;
        };
        WriterTestInput: {
            /** Format: uuid */
            writer_id?: string;
            name: string;
            model_alias: string;
            system_prompt: string;
            /** Format: double */
            temperature: number;
        };
        WriterTestResult: {
            ok: boolean;
            /** Format: uuid */
            run_id: string;
            model_alias: string;
            reply?: string;
            error?: string;
            prompt_tokens: number;
            completion_tokens: number;
            /** Format: double */
            cost_usd?: number;
            cost_known: boolean;
            cost_estimated: boolean;
            latency_ms: number;
        };
        /** @enum {string} */
        RunKind: "critique" | "revision" | "bible_update" | "cowrite" | "compare" | "writer_test";
        /** @enum {string} */
        RunStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /** @description One workflow execution. params holds what started it, result what it produced. */
        Run: {
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["RunKind"];
            status: components["schemas"]["RunStatus"];
            /** Format: uuid */
            project_id?: string;
            /** Format: uuid */
            chapter_id?: string;
            params: {
                [key: string]: unknown;
            };
            result?: {
                [key: string]: unknown;
            };
            error: string;
            /** Format: double */
            cost_usd: number;
            cost_estimated: boolean;
            prompt_tokens: number;
            completion_tokens: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            finished_at?: string;
        };
        /** @description One Server-Sent Event of a run, as stored. seq is the SSE id. */
        RunEvent: {
            /** Format: uuid */
            run_id: string;
            seq: number;
            type: string;
            payload: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        projectId: string;
        chapterId: string;
        versionId: string;
        entryId: string;
        writerId: string;
        runId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listGatewayModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayModels"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listChapters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterSummary"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createChapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChapterCreateInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chapter"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listBibleEntries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BibleEntry"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createBibleEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BibleEntryInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BibleEntry"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateBibleEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entryId: components["parameters"]["entryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BibleEntryInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BibleEntry"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteBibleEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entryId: components["parameters"]["entryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getChapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chapter"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateChapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChapterMetaInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chapter"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteChapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    saveChapterContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChapterContentInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterSaveResult"];
                };
            };
            /** @description The chapter changed since base_hash was read */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listChapterVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterVersionSummary"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createChapterSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnapshotInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterVersion"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getChapterVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
                versionId: components["parameters"]["versionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterVersion"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    restoreChapterVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
                versionId: components["parameters"]["versionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chapter"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listChapterRuns: {
        parameters: {
            query?: {
                kind?: components["schemas"]["RunKind"];
                limit?: number;
            };
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The run after the cancel request */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    streamRunEvents: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listWriters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Writer"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createWriter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WriterInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Writer"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    testWriter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WriterTestInput"];
            };
        };
        responses: {
            /** @description The gateway answered or refused; see ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriterTestResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getWriter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                writerId: components["parameters"]["writerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Writer"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateWriter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                writerId: components["parameters"]["writerId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WriterInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Writer"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteWriter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                writerId: components["parameters"]["writerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    duplicateWriter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                writerId: components["parameters"]["writerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Writer"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
