/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current account and app configuration */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSettings"];
        put: operations["updateSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gateway/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aliases known to the gateway */
        get: operations["listGatewayModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        get: operations["getProject"];
        put: operations["updateProject"];
        post?: never;
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        get: operations["listChapters"];
        put?: never;
        post: operations["createChapter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/bible": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        get: operations["listBibleEntries"];
        put?: never;
        post: operations["createBibleEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bible-entries/{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entryId: components["parameters"]["entryId"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["updateBibleEntry"];
        post?: never;
        delete: operations["deleteBibleEntry"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{chapterId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        get: operations["getChapter"];
        /** Rename or move a chapter */
        put: operations["updateChapter"];
        post?: never;
        delete: operations["deleteChapter"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{chapterId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Save the chapter text; may create an autosave snapshot */
        put: operations["saveChapterContent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{chapterId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        get: operations["listChapterVersions"];
        put?: never;
        /** Take a labelled snapshot by hand */
        post: operations["createChapterSnapshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{chapterId}/versions/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
                versionId: components["parameters"]["versionId"];
            };
            cookie?: never;
        };
        get: operations["getChapterVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{chapterId}/versions/{versionId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
                versionId: components["parameters"]["versionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Snapshot the current text, then replace it with the version */
        post: operations["restoreChapterVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{chapterId}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        /** Runs of a chapter, newest first */
        get: operations["listChapterRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{chapterId}/critiques": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Convene the Guild on a chapter
         * @description Starts a critique run in the background and returns it at once. The
         *     chosen critics read the chapter (split into scenes above the account's
         *     scene token limit) in parallel; follow them through
         *     `GET /api/runs/{runId}/events`. Event types: `critique.plan`,
         *     `writer.started`, `writer.delta`, `writer.retry`, `writer.done`,
         *     `writer.failed`, then the editor-in-chief's `editor.started`,
         *     `editor.delta`, `editor.retry`, `editor.done` (with the prioritized
         *     list; `fallback` is true when the editor failed and the list was
         *     assembled from the critics' notes), then `run.finished`. The validated
         *     critiques are at `GET /api/runs/{runId}/critiques` and the prioritized
         *     list at `GET /api/runs/{runId}/issues`.
         */
        post: operations["startCritique"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}/critiques": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        /** The critics' validated replies for a critique run */
        get: operations["listRunCritiques"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}/issues": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        /** The editor-in-chief's prioritized issue list for a critique run */
        get: operations["listRunIssues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{issueId}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: components["parameters"]["issueId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Accept, reject, edit the fix of, or undo a decision on an issue
         * @description `accepted` with `edited_fix` set is "edit the fix": the author's wording
         *     replaces the suggested fix when the revision is applied. `pending`
         *     undoes a decision; `edited_fix` is kept unless it is sent as null or
         *     empty.
         */
        put: operations["decideIssue"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{chapterId}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        /** Revisions proposed for a chapter, newest first */
        get: operations["listChapterRevisions"];
        put?: never;
        /**
         * Ask the lead writer to apply the accepted issues of a critique run
         * @description Starts a revision run in the background and returns it at once. The
         *     lead writer receives the chapter (scene by scene above the scene
         *     token limit), the story bible and the accepted issues with their
         *     final fix wording, and returns the revised text; the app diffs it
         *     against the chapter into word-level hunks and stores a proposed
         *     revision. Events: `revision.started`, `revision.delta`,
         *     `revision.retry`, `revision.done` (with the revision id), then
         *     `run.finished`.
         */
        post: operations["startRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/revisions/{revisionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revisionId: components["parameters"]["revisionId"];
            };
            cookie?: never;
        };
        get: operations["getRevision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/revisions/{revisionId}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revisionId: components["parameters"]["revisionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply all or some hunks of a proposed revision to the chapter
         * @description Takes a "before revision" snapshot, replaces the chapter text with the
         *     chosen hunks applied, and marks the revision applied. Fails with 409
         *     when the chapter changed since the revision was proposed, or when the
         *     revision was already applied or discarded.
         */
        post: operations["applyRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/revisions/{revisionId}/discard": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revisionId: components["parameters"]["revisionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discard a proposed revision without touching the chapter */
        post: operations["discardRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{chapterId}/bible-updates": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask the bible keeper what the chapter changes in the story bible
         * @description Starts a bible update run in the background and returns it at once.
         *     It also starts by itself when a revision is applied. Events:
         *     `bible.started`, `bible.delta`, `bible.retry`, `bible.done` (with the
         *     stored proposals), then `run.finished`. Proposals wait for the
         *     author's decision at `GET /api/projects/{projectId}/bible/proposals`.
         */
        post: operations["startBibleUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/bible/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        /** Story bible proposals of a project, newest first */
        get: operations["listProjectBibleProposals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}/bible-proposals": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        /** The proposals a bible update run produced */
        get: operations["listRunBibleProposals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bible-proposals/{proposalId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposalId: components["parameters"]["proposalId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Approve (optionally edited) or reject a story bible proposal
         * @description `approved` applies the proposal to the story bible: an addition
         *     creates the entry, an update rewrites the entry's title and fields,
         *     a deletion removes it. `title` and `fields` in the body replace the
         *     proposal's own before it is applied ("edit and approve"). A proposal
         *     can be decided once; an update or deletion whose entry no longer
         *     exists fails with 409.
         */
        put: operations["decideBibleProposal"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop a running run; a finished run is returned unchanged */
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        /**
         * Follow a run as Server-Sent Events
         * @description Replays the stored events with a sequence number above `after` (or
         *     the `Last-Event-ID` header), then follows the run live. Each event has
         *     `id` set to its sequence number, `event` set to its type and `data`
         *     holding the JSON payload. The stream ends after `run.finished`, or
         *     after an `end` event when the run was already over; the browser then
         *     closes the EventSource instead of reconnecting.
         */
        get: operations["streamRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/writers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWriters"];
        put?: never;
        post: operations["createWriter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/writers/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a short sample request through the gateway */
        post: operations["testWriter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/writers/{writerId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                writerId: components["parameters"]["writerId"];
            };
            cookie?: never;
        };
        get: operations["getWriter"];
        put: operations["updateWriter"];
        post?: never;
        delete: operations["deleteWriter"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/writers/{writerId}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                writerId: components["parameters"]["writerId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["duplicateWriter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: {
                code: string;
                message: string;
            };
        };
        User: {
            /** Format: uuid */
            id: string;
            username: string;
            display_name: string;
            /** @enum {string} */
            role: "admin" | "author";
            /** Format: date-time */
            created_at: string;
        };
        Me: {
            user: components["schemas"]["User"];
            app_name: string;
            default_model_alias: string;
            alias_prefix: string;
        };
        Settings: {
            scene_token_limit: number;
            autosave_snapshot_minutes: number;
        };
        SettingsInput: {
            scene_token_limit: number;
            autosave_snapshot_minutes: number;
        };
        GatewayModels: {
            alias_prefix: string;
            /** @description Models whose id starts with the alias prefix */
            aliases: string[];
            all_models: string[];
        };
        Project: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ProjectSummary: components["schemas"]["Project"] & {
            chapter_count: number;
        };
        ProjectInput: {
            name: string;
            description?: string;
        };
        ChapterSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            title: string;
            position: number;
            content_hash: string;
            content_length: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Chapter: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            title: string;
            position: number;
            content_md: string;
            content_hash: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ChapterCreateInput: {
            title: string;
            content_md?: string;
        };
        ChapterMetaInput: {
            title: string;
            position?: number;
        };
        ChapterContentInput: {
            content_md: string;
            /** @description Hash the client last loaded; when set and stale the save is refused with 409 */
            base_hash?: string;
        };
        ChapterSaveResult: {
            chapter: components["schemas"]["Chapter"];
            snapshot_created: boolean;
        };
        ChapterVersionSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            chapter_id: string;
            /** @enum {string} */
            kind: "autosave" | "manual" | "pre_revision" | "pre_restore";
            label: string;
            content_hash: string;
            content_length: number;
            /** Format: date-time */
            created_at: string;
        };
        ChapterVersion: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            chapter_id: string;
            /** @enum {string} */
            kind: "autosave" | "manual" | "pre_revision" | "pre_restore";
            label: string;
            content_md: string;
            content_hash: string;
            /** Format: date-time */
            created_at: string;
        };
        SnapshotInput: {
            label?: string;
        };
        /** @enum {string} */
        BibleSection: "premise" | "character" | "setting" | "timeline" | "style" | "chapter_summary";
        BibleEntry: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            section: components["schemas"]["BibleSection"];
            title: string;
            fields: {
                [key: string]: string;
            };
            /** Format: uuid */
            chapter_id?: string;
            position: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        BibleEntryInput: {
            section: components["schemas"]["BibleSection"];
            title: string;
            fields: {
                [key: string]: string;
            };
            /** Format: uuid */
            chapter_id?: string;
            position?: number;
        };
        /** @enum {string} */
        WriterRole: "critic" | "co-writer";
        Writer: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            model_alias: string;
            system_prompt: string;
            roles: components["schemas"]["WriterRole"][];
            enabled: boolean;
            /** Format: double */
            temperature: number;
            is_system: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        WriterInput: {
            name: string;
            /** @description Defaults to "{APP_NAME}-{slug}" when empty on create */
            model_alias?: string;
            system_prompt: string;
            roles: components["schemas"]["WriterRole"][];
            enabled: boolean;
            /** Format: double */
            temperature: number;
        };
        WriterTestInput: {
            /** Format: uuid */
            writer_id?: string;
            name: string;
            model_alias: string;
            system_prompt: string;
            /** Format: double */
            temperature: number;
        };
        WriterTestResult: {
            ok: boolean;
            /** Format: uuid */
            run_id: string;
            model_alias: string;
            reply?: string;
            error?: string;
            prompt_tokens: number;
            completion_tokens: number;
            /** Format: double */
            cost_usd?: number;
            cost_known: boolean;
            cost_estimated: boolean;
            latency_ms: number;
        };
        /** @enum {string} */
        RunKind: "critique" | "revision" | "bible_update" | "cowrite" | "compare" | "writer_test";
        /** @enum {string} */
        RunStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /** @description One workflow execution. params holds what started it, result what it produced. */
        Run: {
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["RunKind"];
            status: components["schemas"]["RunStatus"];
            /** Format: uuid */
            project_id?: string;
            /** Format: uuid */
            chapter_id?: string;
            params: {
                [key: string]: unknown;
            };
            result?: {
                [key: string]: unknown;
            };
            error: string;
            /** Format: double */
            cost_usd: number;
            cost_estimated: boolean;
            prompt_tokens: number;
            completion_tokens: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            finished_at?: string;
        };
        /** @description One Server-Sent Event of a run, as stored. seq is the SSE id. */
        RunEvent: {
            /** Format: uuid */
            run_id: string;
            seq: number;
            type: string;
            payload: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
        CritiqueStartInput: {
            /** @description Critics to convene; omitted or empty means every enabled writer with the critic role. */
            writer_ids?: string[];
        };
        /** @enum {string} */
        IssueSeverity: "high" | "medium" | "low";
        CritiqueIssue: {
            id: string;
            severity: components["schemas"]["IssueSeverity"];
            quote: string;
            problem: string;
            suggested_fix: string;
            /** @description Byte offset of the quote in the chapter Markdown */
            start: number;
            end: number;
            /** @description False when the quote matched only after normalising punctuation */
            quote_exact: boolean;
        };
        BibleConflict: {
            quote: string;
            conflicts_with: string;
            start: number;
            end: number;
        };
        Critique: {
            writer: string;
            overall: string;
            issues: components["schemas"]["CritiqueIssue"][];
            bible_conflicts: components["schemas"]["BibleConflict"][];
            warnings?: string[];
        };
        /** @enum {string} */
        CritiqueStatus: "running" | "succeeded" | "failed" | "cancelled";
        /** @description One critic's part of a critique run. */
        CritiqueRecord: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            run_id: string;
            /** Format: uuid */
            chapter_id?: string;
            /** Format: uuid */
            writer_id?: string;
            writer_name: string;
            writer_slug: string;
            model_alias: string;
            status: components["schemas"]["CritiqueStatus"];
            critique?: components["schemas"]["Critique"];
            raw_text: string;
            error: string;
            scene_count: number;
            prompt_tokens: number;
            completion_tokens: number;
            /** Format: double */
            cost_usd: number;
            cost_estimated: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            finished_at?: string;
        };
        /** @enum {string} */
        IssueDecision: "pending" | "accepted" | "rejected";
        /** @description A critic's note that an issue merges or restates. */
        IssueSource: {
            /** @description <writer slug>/<issue id> */
            id: string;
            /** Format: uuid */
            critique_id: string;
            /** Format: uuid */
            writer_id: string;
            writer_name: string;
            writer_slug: string;
            issue_id: string;
        };
        /** @description One entry of the editor-in-chief's prioritized list, with the author's decision. */
        Issue: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            run_id: string;
            /** Format: uuid */
            chapter_id?: string;
            position: number;
            /** @description The editor's own id */
            key: string;
            severity: components["schemas"]["IssueSeverity"];
            quote: string;
            problem: string;
            suggested_fix: string;
            start: number;
            end: number;
            quote_exact: boolean;
            sources: components["schemas"]["IssueSource"][];
            decision: components["schemas"]["IssueDecision"];
            /** @description The author's own wording of the fix */
            edited_fix?: string;
            /** Format: date-time */
            decided_at?: string;
            /** @description Hash of the chapter text the critique read */
            content_hash: string;
            /** Format: date-time */
            created_at: string;
        };
        IssueDecisionInput: {
            decision: components["schemas"]["IssueDecision"];
            /** @description The author's own wording of the fix. Omitted keeps the current value; null or empty clears it. */
            edited_fix?: string | null;
        };
        /** @enum {string} */
        RevisionStatus: "proposed" | "applied" | "discarded";
        DiffOp: {
            /** @enum {string} */
            kind: "equal" | "insert" | "delete";
            text: string;
        };
        /** @description One region of change; offsets address the chapter text the revision was computed against. */
        DiffHunk: {
            index: number;
            old_start: number;
            old_end: number;
            old_text: string;
            new_text: string;
            ops: components["schemas"]["DiffOp"][];
            context_before: string;
            context_after: string;
        };
        DiffStats: {
            words_added: number;
            words_removed: number;
            hunks: number;
        };
        SkippedIssue: {
            /** Format: uuid */
            issue_id: string;
            key: string;
            quote: string;
            reason: string;
        };
        /** @description A revised text proposed by the lead writer, as word-level hunks over the chapter. */
        Revision: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            run_id: string;
            /** Format: uuid */
            chapter_id: string;
            /** Format: uuid */
            critique_run_id?: string;
            status: components["schemas"]["RevisionStatus"];
            /** @description True when the chapter changed since the revision was proposed; it can no longer be applied */
            stale: boolean;
            base_hash: string;
            revised_md: string;
            hunks: components["schemas"]["DiffHunk"][];
            stats: components["schemas"]["DiffStats"];
            issue_ids: string[];
            skipped: components["schemas"]["SkippedIssue"][];
            applied_hunks?: number[];
            result_hash: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            decided_at?: string;
        };
        RevisionStartInput: {
            /**
             * Format: uuid
             * @description The critique run whose accepted issues to apply
             */
            run_id: string;
        };
        RevisionApplyInput: {
            /** @description Hunks to apply; omitted means every hunk. */
            hunk_indexes?: number[];
        };
        RevisionApplyResult: {
            chapter: components["schemas"]["Chapter"];
            revision: components["schemas"]["Revision"];
            /**
             * Format: uuid
             * @description The bible update run started by the apply
             */
            bible_run_id?: string;
        };
        /** @enum {string} */
        ProposalAction: "add" | "update" | "delete";
        /** @enum {string} */
        ProposalStatus: "pending" | "approved" | "rejected";
        /** @description A change to the story bible proposed by the bible keeper, waiting for or carrying the author's decision. */
        BibleProposal: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            run_id: string;
            /** Format: uuid */
            project_id: string;
            /** Format: uuid */
            chapter_id?: string;
            /** Format: uuid */
            revision_id?: string;
            action: components["schemas"]["ProposalAction"];
            /**
             * Format: uuid
             * @description The entry to update or delete
             */
            entry_id?: string;
            current?: components["schemas"]["BibleEntry"];
            section: components["schemas"]["BibleSection"];
            title: string;
            fields: {
                [key: string]: string;
            };
            rationale: string;
            status: components["schemas"]["ProposalStatus"];
            /** Format: uuid */
            applied_entry_id?: string;
            position: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            decided_at?: string;
        };
        BibleProposalDecisionInput: {
            /** @enum {string} */
            decision: "approved" | "rejected";
            title?: string;
            fields?: {
                [key: string]: string;
            };
        };
        BibleUpdateStartInput: {
            /**
             * Format: uuid
             * @description The applied revision whose changes the keeper should consider
             */
            revision_id?: string;
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        projectId: string;
        chapterId: string;
        versionId: string;
        entryId: string;
        writerId: string;
        runId: string;
        issueId: string;
        revisionId: string;
        proposalId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listGatewayModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayModels"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listChapters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterSummary"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createChapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChapterCreateInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chapter"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listBibleEntries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BibleEntry"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createBibleEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BibleEntryInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BibleEntry"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateBibleEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entryId: components["parameters"]["entryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BibleEntryInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BibleEntry"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteBibleEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entryId: components["parameters"]["entryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getChapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chapter"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateChapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChapterMetaInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chapter"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteChapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    saveChapterContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChapterContentInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterSaveResult"];
                };
            };
            /** @description The chapter changed since base_hash was read */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listChapterVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterVersionSummary"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createChapterSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnapshotInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterVersion"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getChapterVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
                versionId: components["parameters"]["versionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterVersion"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    restoreChapterVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
                versionId: components["parameters"]["versionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chapter"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listChapterRuns: {
        parameters: {
            query?: {
                kind?: components["schemas"]["RunKind"];
                limit?: number;
            };
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    startCritique: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CritiqueStartInput"];
            };
        };
        responses: {
            /** @description The run that was started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listRunCritiques: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CritiqueRecord"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listRunIssues: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK, in priority order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issue"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    decideIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: components["parameters"]["issueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueDecisionInput"];
            };
        };
        responses: {
            /** @description The issue after the decision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issue"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listChapterRevisions: {
        parameters: {
            query?: {
                status?: components["schemas"]["RevisionStatus"];
                limit?: number;
            };
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Revision"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    startRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionStartInput"];
            };
        };
        responses: {
            /** @description The run that was started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revisionId: components["parameters"]["revisionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Revision"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    applyRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revisionId: components["parameters"]["revisionId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RevisionApplyInput"];
            };
        };
        responses: {
            /** @description The chapter and the revision after the change */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionApplyResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    discardRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revisionId: components["parameters"]["revisionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The discarded revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Revision"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    startBibleUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["BibleUpdateStartInput"];
            };
        };
        responses: {
            /** @description The run that was started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listProjectBibleProposals: {
        parameters: {
            query?: {
                status?: components["schemas"]["ProposalStatus"];
                limit?: number;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BibleProposal"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listRunBibleProposals: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BibleProposal"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    decideBibleProposal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposalId: components["parameters"]["proposalId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BibleProposalDecisionInput"];
            };
        };
        responses: {
            /** @description The proposal after the decision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BibleProposal"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The run after the cancel request */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    streamRunEvents: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listWriters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Writer"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createWriter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WriterInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Writer"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    testWriter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WriterTestInput"];
            };
        };
        responses: {
            /** @description The gateway answered or refused; see ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriterTestResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getWriter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                writerId: components["parameters"]["writerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Writer"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateWriter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                writerId: components["parameters"]["writerId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WriterInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Writer"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteWriter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                writerId: components["parameters"]["writerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    duplicateWriter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                writerId: components["parameters"]["writerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Writer"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
