/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with username and password
         * @description Sets the session cookie (HttpOnly, SameSite=Lax; Secure over HTTPS)
         *     and returns the account. A wrong username is refused exactly like a
         *     wrong password (401, code `invalid_credentials`). After five wrong
         *     passwords for a username from one address, further tries are refused
         *     with 429 (code `too_many_attempts`) and a `Retry-After` header for a
         *     minute, then longer, up to a quarter of an hour. A disabled account
         *     cannot sign in (401, code `account_disabled`).
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out of this browser */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every account (admins only) */
        get: operations["listUsers"];
        put?: never;
        /**
         * Add an account (admins only); there is no sign-up form
         * @description The new account gets its own settings, example writers and system
         *     agents. Usernames are lower-case, 3 to 32 characters; a taken
         *     username answers 409.
         */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change the display name of the signed-in account */
        put: operations["updateAccount"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Change the signed-in account's password
         * @description Requires the current password; the new one needs at least 8
         *     characters. Every other session of the account ends; this browser
         *     receives a fresh session cookie.
         */
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current account and app configuration */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSettings"];
        put: operations["updateSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gateway/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aliases known to the gateway */
        get: operations["listGatewayModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        get: operations["getProject"];
        put: operations["updateProject"];
        post?: never;
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        get: operations["listChapters"];
        put?: never;
        post: operations["createChapter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/bible": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        get: operations["listBibleEntries"];
        put?: never;
        post: operations["createBibleEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bible-entries/{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entryId: components["parameters"]["entryId"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["updateBibleEntry"];
        post?: never;
        delete: operations["deleteBibleEntry"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{chapterId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        get: operations["getChapter"];
        /** Rename or move a chapter */
        put: operations["updateChapter"];
        post?: never;
        delete: operations["deleteChapter"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{chapterId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Save the chapter text; may create an autosave snapshot */
        put: operations["saveChapterContent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{chapterId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        get: operations["listChapterVersions"];
        put?: never;
        /** Take a labelled snapshot by hand */
        post: operations["createChapterSnapshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{chapterId}/versions/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
                versionId: components["parameters"]["versionId"];
            };
            cookie?: never;
        };
        get: operations["getChapterVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{chapterId}/versions/{versionId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
                versionId: components["parameters"]["versionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Snapshot the current text, then replace it with the version */
        post: operations["restoreChapterVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{chapterId}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        /** Runs of a chapter, newest first */
        get: operations["listChapterRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{chapterId}/critiques": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Convene the Guild on a chapter
         * @description Starts a critique run in the background and returns it at once. The
         *     chosen critics read the chapter (split into scenes above the account's
         *     scene token limit) in parallel; follow them through
         *     `GET /api/runs/{runId}/events`. Event types: `critique.plan`,
         *     `writer.started`, `writer.delta`, `writer.retry`, `writer.done`,
         *     `writer.failed`, then the editor-in-chief's `editor.started`,
         *     `editor.delta`, `editor.retry`, `editor.done` (with the prioritized
         *     list; `fallback` is true when the editor failed and the list was
         *     assembled from the critics' notes), then `run.finished`. The validated
         *     critiques are at `GET /api/runs/{runId}/critiques` and the prioritized
         *     list at `GET /api/runs/{runId}/issues`.
         */
        post: operations["startCritique"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}/critiques": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        /** The critics' validated replies for a critique run */
        get: operations["listRunCritiques"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}/issues": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        /** The editor-in-chief's prioritized issue list for a critique run */
        get: operations["listRunIssues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{issueId}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: components["parameters"]["issueId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Accept, reject, edit the fix of, or undo a decision on an issue
         * @description `accepted` with `edited_fix` set is "edit the fix": the author's wording
         *     replaces the suggested fix when the revision is applied. `pending`
         *     undoes a decision; `edited_fix` is kept unless it is sent as null or
         *     empty.
         */
        put: operations["decideIssue"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{chapterId}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        /** Revisions proposed for a chapter, newest first */
        get: operations["listChapterRevisions"];
        put?: never;
        /**
         * Ask the lead writer to apply the accepted issues of a critique run
         * @description Starts a revision run in the background and returns it at once. The
         *     lead writer receives the chapter (scene by scene above the scene
         *     token limit), the story bible and the accepted issues with their
         *     final fix wording, and returns the revised text; the app diffs it
         *     against the chapter into word-level hunks and stores a proposed
         *     revision. Events: `revision.started`, `revision.delta`,
         *     `revision.retry`, `revision.done` (with the revision id), then
         *     `run.finished`.
         */
        post: operations["startRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/revisions/{revisionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revisionId: components["parameters"]["revisionId"];
            };
            cookie?: never;
        };
        get: operations["getRevision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/revisions/{revisionId}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revisionId: components["parameters"]["revisionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply all or some hunks of a proposed revision to the chapter
         * @description Takes a "before revision" snapshot, replaces the chapter text with the
         *     chosen hunks applied, and marks the revision applied. Fails with 409
         *     when the chapter changed since the revision was proposed, or when the
         *     revision was already applied or discarded.
         */
        post: operations["applyRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/revisions/{revisionId}/discard": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revisionId: components["parameters"]["revisionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discard a proposed revision without touching the chapter */
        post: operations["discardRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{chapterId}/bible-updates": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask the bible keeper what the chapter changes in the story bible
         * @description Starts a bible update run in the background and returns it at once.
         *     It also starts by itself when a revision is applied. Events:
         *     `bible.started`, `bible.delta`, `bible.retry`, `bible.done` (with the
         *     stored proposals), then `run.finished`. Proposals wait for the
         *     author's decision at `GET /api/projects/{projectId}/bible/proposals`.
         */
        post: operations["startBibleUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/bible/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        /** Story bible proposals of a project, newest first */
        get: operations["listProjectBibleProposals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}/bible-proposals": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        /** The proposals a bible update run produced */
        get: operations["listRunBibleProposals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bible-proposals/{proposalId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposalId: components["parameters"]["proposalId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Approve (optionally edited) or reject a story bible proposal
         * @description `approved` applies the proposal to the story bible: an addition
         *     creates the entry, an update rewrites the entry's title and fields,
         *     a deletion removes it. `title` and `fields` in the body replace the
         *     proposal's own before it is applied ("edit and approve"). A proposal
         *     can be decided once; an update or deletion whose entry no longer
         *     exists fails with 409.
         */
        put: operations["decideBibleProposal"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{chapterId}/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        /** Recent co-writer drafts of a chapter, newest first */
        get: operations["listChapterDrafts"];
        put?: never;
        /**
         * Ask one co-writer for a draft, or two or three for drafts to compare
         * @description Starts a co-write run (one writer) or a compare run (two or three
         *     writers, same request) in the background and returns it at once. With
         *     `selection` the writers propose text to take the passage's place;
         *     without it they continue from the cursor using `context_before` and
         *     `context_after`. Events: `draft.started`, `draft.delta`,
         *     `draft.retry`, `draft.done` (with the whole draft), `draft.failed`,
         *     then `run.finished`. Drafts are at `GET /api/runs/{runId}/drafts`.
         */
        post: operations["startCowrite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        /** The drafts a co-write or compare run produced */
        get: operations["listRunDrafts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drafts/{draftId}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draftId: components["parameters"]["draftId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Record what the author did with a draft
         * @description `inserted` and `replaced` record that the text went into the chapter
         *     (the editor does the insertion); `discarded` sets it aside; `pending`
         *     takes a discarded draft back. `replaced` is only valid for a draft
         *     made from a selection.
         */
        put: operations["decideDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{chapterId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        /**
         * Every run of a chapter, newest first, with totals
         * @description Runs with a one-line summary each and the counts behind it (critics,
         *     issues and decisions, revision changes, drafts, proposals), the
         *     totals of runs, cost and tokens over every run matching `kind`, and
         *     per-kind counts for the filter. Page through with `before`.
         */
        get: operations["getChapterHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}/calls": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        /** The gateway calls a run made, with cost and tokens per writer */
        get: operations["listRunCalls"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/writers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Acceptance rates and cost per writer, by period and project
         * @description For every writer of the account: issues on the editor-in-chief's list
         *     that cite the writer (an issue counts for every critic it cites) with
         *     the author's decisions and the resulting acceptance rate, drafts and
         *     how many went into the chapter, and cost, tokens and calls per kind
         *     of run. `period` restricts to the last 7, 30 or 90 days; `project_id`
         *     to one novel (writer tests belong to no project and drop out then).
         */
        get: operations["getWriterStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop a running run; a finished run is returned unchanged */
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        /**
         * Follow a run as Server-Sent Events
         * @description Replays the stored events with a sequence number above `after` (or
         *     the `Last-Event-ID` header), then follows the run live. Each event has
         *     `id` set to its sequence number, `event` set to its type and `data`
         *     holding the JSON payload. The stream ends after `run.finished`, or
         *     after an `end` event when the run was already over; the browser then
         *     closes the EventSource instead of reconnecting.
         */
        get: operations["streamRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/writers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWriters"];
        put?: never;
        post: operations["createWriter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/writers/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a short sample request through the gateway */
        post: operations["testWriter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/writers/{writerId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                writerId: components["parameters"]["writerId"];
            };
            cookie?: never;
        };
        get: operations["getWriter"];
        put: operations["updateWriter"];
        post?: never;
        delete: operations["deleteWriter"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/writers/{writerId}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                writerId: components["parameters"]["writerId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["duplicateWriter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: {
                code: string;
                message: string;
            };
        };
        User: {
            /** Format: uuid */
            id: string;
            username: string;
            display_name: string;
            /** @enum {string} */
            role: "admin" | "author";
            /** Format: date-time */
            created_at: string;
        };
        Me: {
            user: components["schemas"]["User"];
            app_name: string;
            default_model_alias: string;
            alias_prefix: string;
        };
        Settings: {
            scene_token_limit: number;
            autosave_snapshot_minutes: number;
        };
        SettingsInput: {
            scene_token_limit: number;
            autosave_snapshot_minutes: number;
        };
        GatewayModels: {
            alias_prefix: string;
            /** @description Models whose id starts with the alias prefix */
            aliases: string[];
            all_models: string[];
        };
        Project: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ProjectSummary: components["schemas"]["Project"] & {
            chapter_count: number;
        };
        ProjectInput: {
            name: string;
            description?: string;
        };
        ChapterSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            title: string;
            position: number;
            content_hash: string;
            content_length: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Chapter: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            title: string;
            position: number;
            content_md: string;
            content_hash: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ChapterCreateInput: {
            title: string;
            content_md?: string;
        };
        ChapterMetaInput: {
            title: string;
            position?: number;
        };
        ChapterContentInput: {
            content_md: string;
            /** @description Hash the client last loaded; when set and stale the save is refused with 409 */
            base_hash?: string;
        };
        ChapterSaveResult: {
            chapter: components["schemas"]["Chapter"];
            snapshot_created: boolean;
        };
        ChapterVersionSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            chapter_id: string;
            /** @enum {string} */
            kind: "autosave" | "manual" | "pre_revision" | "pre_restore";
            label: string;
            content_hash: string;
            content_length: number;
            /** Format: date-time */
            created_at: string;
        };
        ChapterVersion: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            chapter_id: string;
            /** @enum {string} */
            kind: "autosave" | "manual" | "pre_revision" | "pre_restore";
            label: string;
            content_md: string;
            content_hash: string;
            /** Format: date-time */
            created_at: string;
        };
        SnapshotInput: {
            label?: string;
        };
        /** @enum {string} */
        BibleSection: "premise" | "character" | "setting" | "timeline" | "style" | "chapter_summary";
        BibleEntry: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            section: components["schemas"]["BibleSection"];
            title: string;
            fields: {
                [key: string]: string;
            };
            /** Format: uuid */
            chapter_id?: string;
            position: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        BibleEntryInput: {
            section: components["schemas"]["BibleSection"];
            title: string;
            fields: {
                [key: string]: string;
            };
            /** Format: uuid */
            chapter_id?: string;
            position?: number;
        };
        /** @enum {string} */
        WriterRole: "critic" | "co-writer";
        Writer: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            model_alias: string;
            system_prompt: string;
            roles: components["schemas"]["WriterRole"][];
            enabled: boolean;
            /** Format: double */
            temperature: number;
            is_system: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        WriterInput: {
            name: string;
            /** @description Defaults to "{APP_NAME}-{slug}" when empty on create */
            model_alias?: string;
            system_prompt: string;
            roles: components["schemas"]["WriterRole"][];
            enabled: boolean;
            /** Format: double */
            temperature: number;
        };
        WriterTestInput: {
            /** Format: uuid */
            writer_id?: string;
            name: string;
            model_alias: string;
            system_prompt: string;
            /** Format: double */
            temperature: number;
        };
        WriterTestResult: {
            ok: boolean;
            /** Format: uuid */
            run_id: string;
            model_alias: string;
            reply?: string;
            error?: string;
            prompt_tokens: number;
            completion_tokens: number;
            /** Format: double */
            cost_usd?: number;
            cost_known: boolean;
            cost_estimated: boolean;
            latency_ms: number;
        };
        /** @enum {string} */
        RunKind: "critique" | "revision" | "bible_update" | "cowrite" | "compare" | "writer_test";
        /** @enum {string} */
        RunStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /** @description One workflow execution. params holds what started it, result what it produced. */
        Run: {
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["RunKind"];
            status: components["schemas"]["RunStatus"];
            /** Format: uuid */
            project_id?: string;
            /** Format: uuid */
            chapter_id?: string;
            params: {
                [key: string]: unknown;
            };
            result?: {
                [key: string]: unknown;
            };
            error: string;
            /** Format: double */
            cost_usd: number;
            cost_estimated: boolean;
            prompt_tokens: number;
            completion_tokens: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            finished_at?: string;
        };
        /** @description One Server-Sent Event of a run, as stored. seq is the SSE id. */
        RunEvent: {
            /** Format: uuid */
            run_id: string;
            seq: number;
            type: string;
            payload: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
        CritiqueStartInput: {
            /** @description Critics to convene; omitted or empty means every enabled writer with the critic role. */
            writer_ids?: string[];
        };
        /** @enum {string} */
        IssueSeverity: "high" | "medium" | "low";
        CritiqueIssue: {
            id: string;
            severity: components["schemas"]["IssueSeverity"];
            quote: string;
            problem: string;
            suggested_fix: string;
            /** @description Byte offset of the quote in the chapter Markdown */
            start: number;
            end: number;
            /** @description False when the quote matched only after normalising punctuation */
            quote_exact: boolean;
        };
        BibleConflict: {
            quote: string;
            conflicts_with: string;
            start: number;
            end: number;
        };
        Critique: {
            writer: string;
            overall: string;
            issues: components["schemas"]["CritiqueIssue"][];
            bible_conflicts: components["schemas"]["BibleConflict"][];
            warnings?: string[];
        };
        /** @enum {string} */
        CritiqueStatus: "running" | "succeeded" | "failed" | "cancelled";
        /** @description One critic's part of a critique run. */
        CritiqueRecord: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            run_id: string;
            /** Format: uuid */
            chapter_id?: string;
            /** Format: uuid */
            writer_id?: string;
            writer_name: string;
            writer_slug: string;
            model_alias: string;
            status: components["schemas"]["CritiqueStatus"];
            critique?: components["schemas"]["Critique"];
            raw_text: string;
            error: string;
            scene_count: number;
            prompt_tokens: number;
            completion_tokens: number;
            /** Format: double */
            cost_usd: number;
            cost_estimated: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            finished_at?: string;
        };
        /** @enum {string} */
        IssueDecision: "pending" | "accepted" | "rejected";
        /** @description A critic's note that an issue merges or restates. */
        IssueSource: {
            /** @description <writer slug>/<issue id> */
            id: string;
            /** Format: uuid */
            critique_id: string;
            /** Format: uuid */
            writer_id: string;
            writer_name: string;
            writer_slug: string;
            issue_id: string;
        };
        /** @description One entry of the editor-in-chief's prioritized list, with the author's decision. */
        Issue: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            run_id: string;
            /** Format: uuid */
            chapter_id?: string;
            position: number;
            /** @description The editor's own id */
            key: string;
            severity: components["schemas"]["IssueSeverity"];
            quote: string;
            problem: string;
            suggested_fix: string;
            start: number;
            end: number;
            quote_exact: boolean;
            sources: components["schemas"]["IssueSource"][];
            decision: components["schemas"]["IssueDecision"];
            /** @description The author's own wording of the fix */
            edited_fix?: string;
            /** Format: date-time */
            decided_at?: string;
            /** @description Hash of the chapter text the critique read */
            content_hash: string;
            /** Format: date-time */
            created_at: string;
        };
        IssueDecisionInput: {
            decision: components["schemas"]["IssueDecision"];
            /** @description The author's own wording of the fix. Omitted keeps the current value; null or empty clears it. */
            edited_fix?: string | null;
        };
        /** @enum {string} */
        RevisionStatus: "proposed" | "applied" | "discarded";
        DiffOp: {
            /** @enum {string} */
            kind: "equal" | "insert" | "delete";
            text: string;
        };
        /** @description One region of change; offsets address the chapter text the revision was computed against. */
        DiffHunk: {
            index: number;
            old_start: number;
            old_end: number;
            old_text: string;
            new_text: string;
            ops: components["schemas"]["DiffOp"][];
            context_before: string;
            context_after: string;
        };
        DiffStats: {
            words_added: number;
            words_removed: number;
            hunks: number;
        };
        SkippedIssue: {
            /** Format: uuid */
            issue_id: string;
            key: string;
            quote: string;
            reason: string;
        };
        /** @description A revised text proposed by the lead writer, as word-level hunks over the chapter. */
        Revision: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            run_id: string;
            /** Format: uuid */
            chapter_id: string;
            /** Format: uuid */
            critique_run_id?: string;
            status: components["schemas"]["RevisionStatus"];
            /** @description True when the chapter changed since the revision was proposed; it can no longer be applied */
            stale: boolean;
            base_hash: string;
            revised_md: string;
            hunks: components["schemas"]["DiffHunk"][];
            stats: components["schemas"]["DiffStats"];
            issue_ids: string[];
            skipped: components["schemas"]["SkippedIssue"][];
            applied_hunks?: number[];
            result_hash: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            decided_at?: string;
        };
        RevisionStartInput: {
            /**
             * Format: uuid
             * @description The critique run whose accepted issues to apply
             */
            run_id: string;
        };
        RevisionApplyInput: {
            /** @description Hunks to apply; omitted means every hunk. */
            hunk_indexes?: number[];
        };
        RevisionApplyResult: {
            chapter: components["schemas"]["Chapter"];
            revision: components["schemas"]["Revision"];
            /**
             * Format: uuid
             * @description The bible update run started by the apply
             */
            bible_run_id?: string;
        };
        /** @enum {string} */
        ProposalAction: "add" | "update" | "delete";
        /** @enum {string} */
        ProposalStatus: "pending" | "approved" | "rejected";
        /** @description A change to the story bible proposed by the bible keeper, waiting for or carrying the author's decision. */
        BibleProposal: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            run_id: string;
            /** Format: uuid */
            project_id: string;
            /** Format: uuid */
            chapter_id?: string;
            /** Format: uuid */
            revision_id?: string;
            action: components["schemas"]["ProposalAction"];
            /**
             * Format: uuid
             * @description The entry to update or delete
             */
            entry_id?: string;
            current?: components["schemas"]["BibleEntry"];
            section: components["schemas"]["BibleSection"];
            title: string;
            fields: {
                [key: string]: string;
            };
            rationale: string;
            status: components["schemas"]["ProposalStatus"];
            /** Format: uuid */
            applied_entry_id?: string;
            position: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            decided_at?: string;
        };
        BibleProposalDecisionInput: {
            /** @enum {string} */
            decision: "approved" | "rejected";
            title?: string;
            fields?: {
                [key: string]: string;
            };
        };
        BibleUpdateStartInput: {
            /**
             * Format: uuid
             * @description The applied revision whose changes the keeper should consider
             */
            revision_id?: string;
        };
        /** @enum {string} */
        DraftMode: "selection" | "continue";
        /** @enum {string} */
        DraftDecision: "pending" | "inserted" | "replaced" | "discarded";
        /** @enum {string} */
        DraftStatus: "running" | "succeeded" | "failed" | "cancelled";
        /** @description One co-writer's draft for a request, with what the author did with it. */
        Draft: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            run_id: string;
            /** Format: uuid */
            chapter_id?: string;
            /** Format: uuid */
            writer_id?: string;
            writer_name: string;
            writer_slug: string;
            model_alias: string;
            mode: components["schemas"]["DraftMode"];
            instruction: string;
            /** @description The passage the draft was asked to replace */
            selection: string;
            notes: string;
            status: components["schemas"]["DraftStatus"];
            /** @description The draft */
            text: string;
            error: string;
            decision: components["schemas"]["DraftDecision"];
            /** Format: date-time */
            decided_at?: string;
            position: number;
            prompt_tokens: number;
            completion_tokens: number;
            /** Format: double */
            cost_usd: number;
            cost_estimated: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            finished_at?: string;
        };
        CowriteStartInput: {
            /** @description One writer co-writes; two or three compare. */
            writer_ids: string[];
            instruction: string;
            /** @description The selected passage; omit to continue from the cursor */
            selection?: string;
            /** @description Scene notes */
            notes?: string;
            /** @description Text just before the cursor or selection */
            context_before?: string;
            /** @description Text just after */
            context_after?: string;
        };
        DraftDecisionInput: {
            decision: components["schemas"]["DraftDecision"];
        };
        HistoryTotals: {
            runs: number;
            /** Format: double */
            cost_usd: number;
            /** @description True when any part of the cost was estimated from token counts */
            cost_estimated: boolean;
            /** Format: int64 */
            prompt_tokens: number;
            /** Format: int64 */
            completion_tokens: number;
        };
        HistoryKindCount: {
            kind: components["schemas"]["RunKind"];
            count: number;
        };
        CritiqueSummary: {
            critics: number;
            failed: number;
            issues: number;
            accepted: number;
            rejected: number;
            pending: number;
            /** @description ok */
            synthesis: string;
        };
        RevisionSummary: {
            status: components["schemas"]["RevisionStatus"];
            hunks: number;
            applied_hunks: number;
            words_added: number;
            words_removed: number;
        };
        DraftsSummary: {
            count: number;
            inserted: number;
            replaced: number;
            discarded: number;
            pending: number;
        };
        BibleSummary: {
            proposals: number;
            approved: number;
            rejected: number;
            pending: number;
        };
        RunHistoryItem: {
            run: components["schemas"]["Run"];
            /** @description One line saying what the run did and what came of it */
            summary: string;
            writers: string[];
            model_calls: number;
            critique?: components["schemas"]["CritiqueSummary"];
            revision?: components["schemas"]["RevisionSummary"];
            drafts?: components["schemas"]["DraftsSummary"];
            bible?: components["schemas"]["BibleSummary"];
        };
        HistoryPage: {
            items: components["schemas"]["RunHistoryItem"][];
            totals: components["schemas"]["HistoryTotals"];
            kinds: components["schemas"]["HistoryKindCount"][];
            /**
             * Format: date-time
             * @description Pass as `before` to get the next page; absent on the last page
             */
            next_before?: string;
        };
        /** @description One request to the gateway, as recorded. */
        ModelCall: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            run_id?: string;
            /** Format: uuid */
            writer_id?: string;
            writer_name?: string;
            generation_name: string;
            model_alias: string;
            prompt_tokens: number;
            completion_tokens: number;
            /** Format: double */
            cost_usd: number;
            cost_estimated: boolean;
            latency_ms: number;
            /** @enum {string} */
            status: "ok" | "error";
            error: string;
            /** Format: date-time */
            created_at: string;
        };
        KindCost: {
            /** @description A run kind */
            kind: string;
            calls: number;
            /** Format: double */
            cost_usd: number;
            cost_estimated: boolean;
            /** Format: int64 */
            prompt_tokens: number;
            /** Format: int64 */
            completion_tokens: number;
        };
        IssueStats: {
            /** @description Issues on the editor-in-chief's list that cite this writer */
            listed: number;
            accepted: number;
            rejected: number;
            pending: number;
            /**
             * Format: double
             * @description accepted / (accepted + rejected); absent until something was decided
             */
            acceptance_rate?: number;
        };
        DraftStats: {
            /** @description Drafts the writer finished */
            count: number;
            /** @description Inserted or replaced */
            used: number;
            discarded: number;
            pending: number;
            /**
             * Format: double
             * @description used / (used + discarded); absent until something was decided
             */
            acceptance_rate?: number;
        };
        WriterStats: {
            /** Format: uuid */
            writer_id: string;
            name: string;
            slug: string;
            model_alias: string;
            enabled: boolean;
            is_system: boolean;
            roles: components["schemas"]["WriterRole"][];
            /** @description Critiques the writer finished */
            critiques: number;
            issues: components["schemas"]["IssueStats"];
            drafts: components["schemas"]["DraftStats"];
            calls: number;
            /** Format: double */
            cost_usd: number;
            cost_estimated: boolean;
            /** Format: int64 */
            prompt_tokens: number;
            /** Format: int64 */
            completion_tokens: number;
            by_kind: components["schemas"]["KindCost"][];
        };
        WriterStatsPage: {
            period: string;
            /** Format: uuid */
            project_id?: string;
            writers: components["schemas"]["WriterStats"][];
            /** @description Everything in the period and project */
            totals: components["schemas"]["KindCost"];
        };
        LoginInput: {
            username: string;
            password: string;
        };
        UserCreateInput: {
            username: string;
            display_name?: string;
            password: string;
            /** @enum {string} */
            role: "admin" | "author";
        };
        AccountInput: {
            display_name: string;
        };
        PasswordChangeInput: {
            current_password: string;
            new_password: string;
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        projectId: string;
        chapterId: string;
        versionId: string;
        entryId: string;
        writerId: string;
        runId: string;
        issueId: string;
        revisionId: string;
        proposalId: string;
        draftId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInput"];
            };
        };
        responses: {
            /** @description Signed in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session cookie was cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeInput"];
            };
        };
        responses: {
            /** @description Changed; a fresh session cookie was set */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listGatewayModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayModels"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listChapters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterSummary"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createChapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChapterCreateInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chapter"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listBibleEntries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BibleEntry"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createBibleEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BibleEntryInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BibleEntry"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateBibleEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entryId: components["parameters"]["entryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BibleEntryInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BibleEntry"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteBibleEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entryId: components["parameters"]["entryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getChapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chapter"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateChapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChapterMetaInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chapter"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteChapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    saveChapterContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChapterContentInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterSaveResult"];
                };
            };
            /** @description The chapter changed since base_hash was read */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listChapterVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterVersionSummary"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createChapterSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnapshotInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterVersion"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getChapterVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
                versionId: components["parameters"]["versionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterVersion"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    restoreChapterVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
                versionId: components["parameters"]["versionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chapter"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listChapterRuns: {
        parameters: {
            query?: {
                kind?: components["schemas"]["RunKind"];
                limit?: number;
            };
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    startCritique: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CritiqueStartInput"];
            };
        };
        responses: {
            /** @description The run that was started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listRunCritiques: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CritiqueRecord"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listRunIssues: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK, in priority order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issue"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    decideIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: components["parameters"]["issueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueDecisionInput"];
            };
        };
        responses: {
            /** @description The issue after the decision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issue"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listChapterRevisions: {
        parameters: {
            query?: {
                status?: components["schemas"]["RevisionStatus"];
                limit?: number;
            };
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Revision"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    startRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionStartInput"];
            };
        };
        responses: {
            /** @description The run that was started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revisionId: components["parameters"]["revisionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Revision"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    applyRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revisionId: components["parameters"]["revisionId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RevisionApplyInput"];
            };
        };
        responses: {
            /** @description The chapter and the revision after the change */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionApplyResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    discardRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revisionId: components["parameters"]["revisionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The discarded revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Revision"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    startBibleUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["BibleUpdateStartInput"];
            };
        };
        responses: {
            /** @description The run that was started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listProjectBibleProposals: {
        parameters: {
            query?: {
                status?: components["schemas"]["ProposalStatus"];
                limit?: number;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BibleProposal"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listRunBibleProposals: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BibleProposal"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    decideBibleProposal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposalId: components["parameters"]["proposalId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BibleProposalDecisionInput"];
            };
        };
        responses: {
            /** @description The proposal after the decision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BibleProposal"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listChapterDrafts: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    startCowrite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CowriteStartInput"];
            };
        };
        responses: {
            /** @description The run that was started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listRunDrafts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    decideDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draftId: components["parameters"]["draftId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftDecisionInput"];
            };
        };
        responses: {
            /** @description The draft after the decision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getChapterHistory: {
        parameters: {
            query?: {
                kind?: components["schemas"]["RunKind"];
                limit?: number;
                before?: string;
            };
            header?: never;
            path: {
                chapterId: components["parameters"]["chapterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listRunCalls: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelCall"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getWriterStats: {
        parameters: {
            query?: {
                period?: "7d" | "30d" | "90d" | "all";
                project_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriterStatsPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The run after the cancel request */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    streamRunEvents: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listWriters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Writer"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createWriter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WriterInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Writer"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    testWriter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WriterTestInput"];
            };
        };
        responses: {
            /** @description The gateway answered or refused; see ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriterTestResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getWriter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                writerId: components["parameters"]["writerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Writer"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateWriter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                writerId: components["parameters"]["writerId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WriterInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Writer"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteWriter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                writerId: components["parameters"]["writerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    duplicateWriter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                writerId: components["parameters"]["writerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Writer"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
