// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BibleSection.
const (
	BibleSectionChapterSummary BibleSection = "chapter_summary"
	BibleSectionCharacter      BibleSection = "character"
	BibleSectionPremise        BibleSection = "premise"
	BibleSectionSetting        BibleSection = "setting"
	BibleSectionStyle          BibleSection = "style"
	BibleSectionTimeline       BibleSection = "timeline"
)

// Valid indicates whether the value is a known member of the BibleSection enum.
func (e BibleSection) Valid() bool {
	switch e {
	case BibleSectionChapterSummary:
		return true
	case BibleSectionCharacter:
		return true
	case BibleSectionPremise:
		return true
	case BibleSectionSetting:
		return true
	case BibleSectionStyle:
		return true
	case BibleSectionTimeline:
		return true
	default:
		return false
	}
}

// Defines values for ChapterVersionKind.
const (
	ChapterVersionKindAutosave    ChapterVersionKind = "autosave"
	ChapterVersionKindManual      ChapterVersionKind = "manual"
	ChapterVersionKindPreRestore  ChapterVersionKind = "pre_restore"
	ChapterVersionKindPreRevision ChapterVersionKind = "pre_revision"
)

// Valid indicates whether the value is a known member of the ChapterVersionKind enum.
func (e ChapterVersionKind) Valid() bool {
	switch e {
	case ChapterVersionKindAutosave:
		return true
	case ChapterVersionKindManual:
		return true
	case ChapterVersionKindPreRestore:
		return true
	case ChapterVersionKindPreRevision:
		return true
	default:
		return false
	}
}

// Defines values for ChapterVersionSummaryKind.
const (
	ChapterVersionSummaryKindAutosave    ChapterVersionSummaryKind = "autosave"
	ChapterVersionSummaryKindManual      ChapterVersionSummaryKind = "manual"
	ChapterVersionSummaryKindPreRestore  ChapterVersionSummaryKind = "pre_restore"
	ChapterVersionSummaryKindPreRevision ChapterVersionSummaryKind = "pre_revision"
)

// Valid indicates whether the value is a known member of the ChapterVersionSummaryKind enum.
func (e ChapterVersionSummaryKind) Valid() bool {
	switch e {
	case ChapterVersionSummaryKindAutosave:
		return true
	case ChapterVersionSummaryKindManual:
		return true
	case ChapterVersionSummaryKindPreRestore:
		return true
	case ChapterVersionSummaryKindPreRevision:
		return true
	default:
		return false
	}
}

// Defines values for CritiqueStatus.
const (
	CritiqueStatusCancelled CritiqueStatus = "cancelled"
	CritiqueStatusFailed    CritiqueStatus = "failed"
	CritiqueStatusRunning   CritiqueStatus = "running"
	CritiqueStatusSucceeded CritiqueStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the CritiqueStatus enum.
func (e CritiqueStatus) Valid() bool {
	switch e {
	case CritiqueStatusCancelled:
		return true
	case CritiqueStatusFailed:
		return true
	case CritiqueStatusRunning:
		return true
	case CritiqueStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for IssueDecision.
const (
	Accepted IssueDecision = "accepted"
	Pending  IssueDecision = "pending"
	Rejected IssueDecision = "rejected"
)

// Valid indicates whether the value is a known member of the IssueDecision enum.
func (e IssueDecision) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Pending:
		return true
	case Rejected:
		return true
	default:
		return false
	}
}

// Defines values for IssueSeverity.
const (
	High   IssueSeverity = "high"
	Low    IssueSeverity = "low"
	Medium IssueSeverity = "medium"
)

// Valid indicates whether the value is a known member of the IssueSeverity enum.
func (e IssueSeverity) Valid() bool {
	switch e {
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	default:
		return false
	}
}

// Defines values for RunKind.
const (
	RunKindBibleUpdate RunKind = "bible_update"
	RunKindCompare     RunKind = "compare"
	RunKindCowrite     RunKind = "cowrite"
	RunKindCritique    RunKind = "critique"
	RunKindRevision    RunKind = "revision"
	RunKindWriterTest  RunKind = "writer_test"
)

// Valid indicates whether the value is a known member of the RunKind enum.
func (e RunKind) Valid() bool {
	switch e {
	case RunKindBibleUpdate:
		return true
	case RunKindCompare:
		return true
	case RunKindCowrite:
		return true
	case RunKindCritique:
		return true
	case RunKindRevision:
		return true
	case RunKindWriterTest:
		return true
	default:
		return false
	}
}

// Defines values for RunStatus.
const (
	RunStatusCancelled RunStatus = "cancelled"
	RunStatusFailed    RunStatus = "failed"
	RunStatusQueued    RunStatus = "queued"
	RunStatusRunning   RunStatus = "running"
	RunStatusSucceeded RunStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the RunStatus enum.
func (e RunStatus) Valid() bool {
	switch e {
	case RunStatusCancelled:
		return true
	case RunStatusFailed:
		return true
	case RunStatusQueued:
		return true
	case RunStatusRunning:
		return true
	case RunStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	Admin  UserRole = "admin"
	Author UserRole = "author"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Author:
		return true
	default:
		return false
	}
}

// Defines values for WriterRole.
const (
	CoWriter WriterRole = "co-writer"
	Critic   WriterRole = "critic"
)

// Valid indicates whether the value is a known member of the WriterRole enum.
func (e WriterRole) Valid() bool {
	switch e {
	case CoWriter:
		return true
	case Critic:
		return true
	default:
		return false
	}
}

// BibleConflict defines model for BibleConflict.
type BibleConflict struct {
	ConflictsWith string `json:"conflicts_with"`
	End           int    `json:"end"`
	Quote         string `json:"quote"`
	Start         int    `json:"start"`
}

// BibleEntry defines model for BibleEntry.
type BibleEntry struct {
	ChapterId *openapi_types.UUID `json:"chapter_id,omitempty"`
	CreatedAt time.Time           `json:"created_at"`
	Fields    map[string]string   `json:"fields"`
	Id        openapi_types.UUID  `json:"id"`
	Position  int                 `json:"position"`
	ProjectId openapi_types.UUID  `json:"project_id"`
	Section   BibleSection        `json:"section"`
	Title     string              `json:"title"`
	UpdatedAt time.Time           `json:"updated_at"`
}

// BibleEntryInput defines model for BibleEntryInput.
type BibleEntryInput struct {
	ChapterId *openapi_types.UUID `json:"chapter_id,omitempty"`
	Fields    map[string]string   `json:"fields"`
	Position  *int                `json:"position,omitempty"`
	Section   BibleSection        `json:"section"`
	Title     string              `json:"title"`
}

// BibleSection defines model for BibleSection.
type BibleSection string

// Chapter defines model for Chapter.
type Chapter struct {
	ContentHash string             `json:"content_hash"`
	ContentMd   string             `json:"content_md"`
	CreatedAt   time.Time          `json:"created_at"`
	Id          openapi_types.UUID `json:"id"`
	Position    int                `json:"position"`
	ProjectId   openapi_types.UUID `json:"project_id"`
	Title       string             `json:"title"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

// ChapterContentInput defines model for ChapterContentInput.
type ChapterContentInput struct {
	// BaseHash Hash the client last loaded; when set and stale the save is refused with 409
	BaseHash  *string `json:"base_hash,omitempty"`
	ContentMd string  `json:"content_md"`
}

// ChapterCreateInput defines model for ChapterCreateInput.
type ChapterCreateInput struct {
	ContentMd *string `json:"content_md,omitempty"`
	Title     string  `json:"title"`
}

// ChapterMetaInput defines model for ChapterMetaInput.
type ChapterMetaInput struct {
	Position *int   `json:"position,omitempty"`
	Title    string `json:"title"`
}

// ChapterSaveResult defines model for ChapterSaveResult.
type ChapterSaveResult struct {
	Chapter         Chapter `json:"chapter"`
	SnapshotCreated bool    `json:"snapshot_created"`
}

// ChapterSummary defines model for ChapterSummary.
type ChapterSummary struct {
	ContentHash   string             `json:"content_hash"`
	ContentLength int                `json:"content_length"`
	CreatedAt     time.Time          `json:"created_at"`
	Id            openapi_types.UUID `json:"id"`
	Position      int                `json:"position"`
	ProjectId     openapi_types.UUID `json:"project_id"`
	Title         string             `json:"title"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

// ChapterVersion defines model for ChapterVersion.
type ChapterVersion struct {
	ChapterId   openapi_types.UUID `json:"chapter_id"`
	ContentHash string             `json:"content_hash"`
	ContentMd   string             `json:"content_md"`
	CreatedAt   time.Time          `json:"created_at"`
	Id          openapi_types.UUID `json:"id"`
	Kind        ChapterVersionKind `json:"kind"`
	Label       string             `json:"label"`
}

// ChapterVersionKind defines model for ChapterVersion.Kind.
type ChapterVersionKind string

// ChapterVersionSummary defines model for ChapterVersionSummary.
type ChapterVersionSummary struct {
	ChapterId     openapi_types.UUID        `json:"chapter_id"`
	ContentHash   string                    `json:"content_hash"`
	ContentLength int                       `json:"content_length"`
	CreatedAt     time.Time                 `json:"created_at"`
	Id            openapi_types.UUID        `json:"id"`
	Kind          ChapterVersionSummaryKind `json:"kind"`
	Label         string                    `json:"label"`
}

// ChapterVersionSummaryKind defines model for ChapterVersionSummary.Kind.
type ChapterVersionSummaryKind string

// Critique defines model for Critique.
type Critique struct {
	BibleConflicts []BibleConflict `json:"bible_conflicts"`
	Issues         []CritiqueIssue `json:"issues"`
	Overall        string          `json:"overall"`
	Warnings       *[]string       `json:"warnings,omitempty"`
	Writer         string          `json:"writer"`
}

// CritiqueIssue defines model for CritiqueIssue.
type CritiqueIssue struct {
	End     int    `json:"end"`
	Id      string `json:"id"`
	Problem string `json:"problem"`
	Quote   string `json:"quote"`

	// QuoteExact False when the quote matched only after normalising punctuation
	QuoteExact bool          `json:"quote_exact"`
	Severity   IssueSeverity `json:"severity"`

	// Start Byte offset of the quote in the chapter Markdown
	Start        int    `json:"start"`
	SuggestedFix string `json:"suggested_fix"`
}

// CritiqueRecord One critic's part of a critique run.
type CritiqueRecord struct {
	ChapterId        *openapi_types.UUID `json:"chapter_id,omitempty"`
	CompletionTokens int                 `json:"completion_tokens"`
	CostEstimated    bool                `json:"cost_estimated"`
	CostUsd          float64             `json:"cost_usd"`
	CreatedAt        time.Time           `json:"created_at"`
	Critique         *Critique           `json:"critique,omitempty"`
	Error            string              `json:"error"`
	FinishedAt       *time.Time          `json:"finished_at,omitempty"`
	Id               openapi_types.UUID  `json:"id"`
	ModelAlias       string              `json:"model_alias"`
	PromptTokens     int                 `json:"prompt_tokens"`
	RawText          string              `json:"raw_text"`
	RunId            openapi_types.UUID  `json:"run_id"`
	SceneCount       int                 `json:"scene_count"`
	Status           CritiqueStatus      `json:"status"`
	WriterId         *openapi_types.UUID `json:"writer_id,omitempty"`
	WriterName       string              `json:"writer_name"`
	WriterSlug       string              `json:"writer_slug"`
}

// CritiqueStartInput defines model for CritiqueStartInput.
type CritiqueStartInput struct {
	// WriterIds Critics to convene; omitted or empty means every enabled writer with the critic role.
	WriterIds *[]openapi_types.UUID `json:"writer_ids,omitempty"`
}

// CritiqueStatus defines model for CritiqueStatus.
type CritiqueStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// GatewayModels defines model for GatewayModels.
type GatewayModels struct {
	AliasPrefix string `json:"alias_prefix"`

	// Aliases Models whose id starts with the alias prefix
	Aliases   []string `json:"aliases"`
	AllModels []string `json:"all_models"`
}

// Issue One entry of the editor-in-chief's prioritized list, with the author's decision.
type Issue struct {
	ChapterId *openapi_types.UUID `json:"chapter_id,omitempty"`

	// ContentHash Hash of the chapter text the critique read
	ContentHash string        `json:"content_hash"`
	CreatedAt   time.Time     `json:"created_at"`
	DecidedAt   *time.Time    `json:"decided_at,omitempty"`
	Decision    IssueDecision `json:"decision"`

	// EditedFix The author's own wording of the fix
	EditedFix *string            `json:"edited_fix,omitempty"`
	End       int                `json:"end"`
	Id        openapi_types.UUID `json:"id"`

	// Key The editor's own id
	Key          string             `json:"key"`
	Position     int                `json:"position"`
	Problem      string             `json:"problem"`
	Quote        string             `json:"quote"`
	QuoteExact   bool               `json:"quote_exact"`
	RunId        openapi_types.UUID `json:"run_id"`
	Severity     IssueSeverity      `json:"severity"`
	Sources      []IssueSource      `json:"sources"`
	Start        int                `json:"start"`
	SuggestedFix string             `json:"suggested_fix"`
}

// IssueDecision defines model for IssueDecision.
type IssueDecision string

// IssueSeverity defines model for IssueSeverity.
type IssueSeverity string

// IssueSource A critic's note that an issue merges or restates.
type IssueSource struct {
	CritiqueId openapi_types.UUID `json:"critique_id"`

	// Id <writer slug>/<issue id>
	Id         string             `json:"id"`
	IssueId    string             `json:"issue_id"`
	WriterId   openapi_types.UUID `json:"writer_id"`
	WriterName string             `json:"writer_name"`
	WriterSlug string             `json:"writer_slug"`
}

// Me defines model for Me.
type Me struct {
	AliasPrefix       string `json:"alias_prefix"`
	AppName           string `json:"app_name"`
	DefaultModelAlias string `json:"default_model_alias"`
	User              User   `json:"user"`
}

// Project defines model for Project.
type Project struct {
	CreatedAt   time.Time          `json:"created_at"`
	Description string             `json:"description"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

// ProjectInput defines model for ProjectInput.
type ProjectInput struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// ProjectSummary defines model for ProjectSummary.
type ProjectSummary struct {
	ChapterCount int                `json:"chapter_count"`
	CreatedAt    time.Time          `json:"created_at"`
	Description  string             `json:"description"`
	Id           openapi_types.UUID `json:"id"`
	Name         string             `json:"name"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

// Run One workflow execution. params holds what started it, result what it produced.
type Run struct {
	ChapterId        *openapi_types.UUID     `json:"chapter_id,omitempty"`
	CompletionTokens int                     `json:"completion_tokens"`
	CostEstimated    bool                    `json:"cost_estimated"`
	CostUsd          float64                 `json:"cost_usd"`
	CreatedAt        time.Time               `json:"created_at"`
	Error            string                  `json:"error"`
	FinishedAt       *time.Time              `json:"finished_at,omitempty"`
	Id               openapi_types.UUID      `json:"id"`
	Kind             RunKind                 `json:"kind"`
	Params           map[string]interface{}  `json:"params"`
	ProjectId        *openapi_types.UUID     `json:"project_id,omitempty"`
	PromptTokens     int                     `json:"prompt_tokens"`
	Result           *map[string]interface{} `json:"result,omitempty"`
	StartedAt        *time.Time              `json:"started_at,omitempty"`
	Status           RunStatus               `json:"status"`
}

// RunEvent One Server-Sent Event of a run, as stored. seq is the SSE id.
type RunEvent struct {
	CreatedAt time.Time              `json:"created_at"`
	Payload   map[string]interface{} `json:"payload"`
	RunId     openapi_types.UUID     `json:"run_id"`
	Seq       int                    `json:"seq"`
	Type      string                 `json:"type"`
}

// RunKind defines model for RunKind.
type RunKind string

// RunStatus defines model for RunStatus.
type RunStatus string

// Settings defines model for Settings.
type Settings struct {
	AutosaveSnapshotMinutes int `json:"autosave_snapshot_minutes"`
	SceneTokenLimit         int `json:"scene_token_limit"`
}

// SettingsInput defines model for SettingsInput.
type SettingsInput struct {
	AutosaveSnapshotMinutes int `json:"autosave_snapshot_minutes"`
	SceneTokenLimit         int `json:"scene_token_limit"`
}

// SnapshotInput defines model for SnapshotInput.
type SnapshotInput struct {
	Label *string `json:"label,omitempty"`
}

// User defines model for User.
type User struct {
	CreatedAt   time.Time          `json:"created_at"`
	DisplayName string             `json:"display_name"`
	Id          openapi_types.UUID `json:"id"`
	Role        UserRole           `json:"role"`
	Username    string             `json:"username"`
}

// UserRole defines model for User.Role.
type UserRole string

// Writer defines model for Writer.
type Writer struct {
	CreatedAt    time.Time          `json:"created_at"`
	Enabled      bool               `json:"enabled"`
	Id           openapi_types.UUID `json:"id"`
	IsSystem     bool               `json:"is_system"`
	ModelAlias   string             `json:"model_alias"`
	Name         string             `json:"name"`
	Roles        []WriterRole       `json:"roles"`
	Slug         string             `json:"slug"`
	SystemPrompt string             `json:"system_prompt"`
	Temperature  float64            `json:"temperature"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

// WriterInput defines model for WriterInput.
type WriterInput struct {
	Enabled bool `json:"enabled"`

	// ModelAlias Defaults to "{APP_NAME}-{slug}" when empty on create
	ModelAlias   *string      `json:"model_alias,omitempty"`
	Name         string       `json:"name"`
	Roles        []WriterRole `json:"roles"`
	SystemPrompt string       `json:"system_prompt"`
	Temperature  float64      `json:"temperature"`
}

// WriterRole defines model for WriterRole.
type WriterRole string

// WriterTestInput defines model for WriterTestInput.
type WriterTestInput struct {
	ModelAlias   string              `json:"model_alias"`
	Name         string              `json:"name"`
	SystemPrompt string              `json:"system_prompt"`
	Temperature  float64             `json:"temperature"`
	WriterId     *openapi_types.UUID `json:"writer_id,omitempty"`
}

// WriterTestResult defines model for WriterTestResult.
type WriterTestResult struct {
	CompletionTokens int                `json:"completion_tokens"`
	CostEstimated    bool               `json:"cost_estimated"`
	CostKnown        bool               `json:"cost_known"`
	CostUsd          *float64           `json:"cost_usd,omitempty"`
	Error            *string            `json:"error,omitempty"`
	LatencyMs        int                `json:"latency_ms"`
	ModelAlias       string             `json:"model_alias"`
	Ok               bool               `json:"ok"`
	PromptTokens     int                `json:"prompt_tokens"`
	Reply            *string            `json:"reply,omitempty"`
	RunId            openapi_types.UUID `json:"run_id"`
}

// ChapterId defines model for chapterId.
type ChapterId = openapi_types.UUID

// EntryId defines model for entryId.
type EntryId = openapi_types.UUID

// ProjectId defines model for projectId.
type ProjectId = openapi_types.UUID

// RunId defines model for runId.
type RunId = openapi_types.UUID

// VersionId defines model for versionId.
type VersionId = openapi_types.UUID

// WriterId defines model for writerId.
type WriterId = openapi_types.UUID

// Error defines model for Error.
type Error = ErrorResponse

// ListChapterRunsParams defines parameters for ListChapterRuns.
type ListChapterRunsParams struct {
	Kind  *RunKind `form:"kind,omitempty" json:"kind,omitempty"`
	Limit *int     `form:"limit,omitempty" json:"limit,omitempty"`
}

// StreamRunEventsParams defines parameters for StreamRunEvents.
type StreamRunEventsParams struct {
	After *int `form:"after,omitempty" json:"after,omitempty"`
}

// UpdateBibleEntryJSONRequestBody defines body for UpdateBibleEntry for application/json ContentType.
type UpdateBibleEntryJSONRequestBody = BibleEntryInput

// UpdateChapterJSONRequestBody defines body for UpdateChapter for application/json ContentType.
type UpdateChapterJSONRequestBody = ChapterMetaInput

// SaveChapterContentJSONRequestBody defines body for SaveChapterContent for application/json ContentType.
type SaveChapterContentJSONRequestBody = ChapterContentInput

// StartCritiqueJSONRequestBody defines body for StartCritique for application/json ContentType.
type StartCritiqueJSONRequestBody = CritiqueStartInput

// CreateChapterSnapshotJSONRequestBody defines body for CreateChapterSnapshot for application/json ContentType.
type CreateChapterSnapshotJSONRequestBody = SnapshotInput

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = ProjectInput

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody = ProjectInput

// CreateBibleEntryJSONRequestBody defines body for CreateBibleEntry for application/json ContentType.
type CreateBibleEntryJSONRequestBody = BibleEntryInput

// CreateChapterJSONRequestBody defines body for CreateChapter for application/json ContentType.
type CreateChapterJSONRequestBody = ChapterCreateInput

// UpdateSettingsJSONRequestBody defines body for UpdateSettings for application/json ContentType.
type UpdateSettingsJSONRequestBody = SettingsInput

// CreateWriterJSONRequestBody defines body for CreateWriter for application/json ContentType.
type CreateWriterJSONRequestBody = WriterInput

// TestWriterJSONRequestBody defines body for TestWriter for application/json ContentType.
type TestWriterJSONRequestBody = WriterTestInput

// UpdateWriterJSONRequestBody defines body for UpdateWriter for application/json ContentType.
type UpdateWriterJSONRequestBody = WriterInput

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (DELETE /api/bible-entries/{entryId})
	DeleteBibleEntry(w http.ResponseWriter, r *http.Request, entryId EntryId)

	// (PUT /api/bible-entries/{entryId})
	UpdateBibleEntry(w http.ResponseWriter, r *http.Request, entryId EntryId)

	// (DELETE /api/chapters/{chapterId})
	DeleteChapter(w http.ResponseWriter, r *http.Request, chapterId ChapterId)

	// (GET /api/chapters/{chapterId})
	GetChapter(w http.ResponseWriter, r *http.Request, chapterId ChapterId)
	// UpdateChapter Rename or move a chapter
	// (PUT /api/chapters/{chapterId})
	UpdateChapter(w http.ResponseWriter, r *http.Request, chapterId ChapterId)
	// SaveChapterContent Save the chapter text; may create an autosave snapshot
	// (PUT /api/chapters/{chapterId}/content)
	SaveChapterContent(w http.ResponseWriter, r *http.Request, chapterId ChapterId)
	// StartCritique Convene the Guild on a chapter
	// (POST /api/chapters/{chapterId}/critiques)
	StartCritique(w http.ResponseWriter, r *http.Request, chapterId ChapterId)
	// ListChapterRuns Runs of a chapter, newest first
	// (GET /api/chapters/{chapterId}/runs)
	ListChapterRuns(w http.ResponseWriter, r *http.Request, chapterId ChapterId, params ListChapterRunsParams)

	// (GET /api/chapters/{chapterId}/versions)
	ListChapterVersions(w http.ResponseWriter, r *http.Request, chapterId ChapterId)
	// CreateChapterSnapshot Take a labelled snapshot by hand
	// (POST /api/chapters/{chapterId}/versions)
	CreateChapterSnapshot(w http.ResponseWriter, r *http.Request, chapterId ChapterId)

	// (GET /api/chapters/{chapterId}/versions/{versionId})
	GetChapterVersion(w http.ResponseWriter, r *http.Request, chapterId ChapterId, versionId VersionId)
	// RestoreChapterVersion Snapshot the current text, then replace it with the version
	// (POST /api/chapters/{chapterId}/versions/{versionId}/restore)
	RestoreChapterVersion(w http.ResponseWriter, r *http.Request, chapterId ChapterId, versionId VersionId)
	// ListGatewayModels Aliases known to the gateway
	// (GET /api/gateway/models)
	ListGatewayModels(w http.ResponseWriter, r *http.Request)
	// GetMe Current account and app configuration
	// (GET /api/me)
	GetMe(w http.ResponseWriter, r *http.Request)

	// (GET /api/projects)
	ListProjects(w http.ResponseWriter, r *http.Request)

	// (POST /api/projects)
	CreateProject(w http.ResponseWriter, r *http.Request)

	// (DELETE /api/projects/{projectId})
	DeleteProject(w http.ResponseWriter, r *http.Request, projectId ProjectId)

	// (GET /api/projects/{projectId})
	GetProject(w http.ResponseWriter, r *http.Request, projectId ProjectId)

	// (PUT /api/projects/{projectId})
	UpdateProject(w http.ResponseWriter, r *http.Request, projectId ProjectId)

	// (GET /api/projects/{projectId}/bible)
	ListBibleEntries(w http.ResponseWriter, r *http.Request, projectId ProjectId)

	// (POST /api/projects/{projectId}/bible)
	CreateBibleEntry(w http.ResponseWriter, r *http.Request, projectId ProjectId)

	// (GET /api/projects/{projectId}/chapters)
	ListChapters(w http.ResponseWriter, r *http.Request, projectId ProjectId)

	// (POST /api/projects/{projectId}/chapters)
	CreateChapter(w http.ResponseWriter, r *http.Request, projectId ProjectId)

	// (GET /api/runs/{runId})
	GetRun(w http.ResponseWriter, r *http.Request, runId RunId)
	// CancelRun Stop a running run; a finished run is returned unchanged
	// (POST /api/runs/{runId}/cancel)
	CancelRun(w http.ResponseWriter, r *http.Request, runId RunId)
	// ListRunCritiques The critics' validated replies for a critique run
	// (GET /api/runs/{runId}/critiques)
	ListRunCritiques(w http.ResponseWriter, r *http.Request, runId RunId)
	// StreamRunEvents Follow a run as Server-Sent Events
	// (GET /api/runs/{runId}/events)
	StreamRunEvents(w http.ResponseWriter, r *http.Request, runId RunId, params StreamRunEventsParams)
	// ListRunIssues The editor-in-chief's prioritized issue list for a critique run
	// (GET /api/runs/{runId}/issues)
	ListRunIssues(w http.ResponseWriter, r *http.Request, runId RunId)

	// (GET /api/settings)
	GetSettings(w http.ResponseWriter, r *http.Request)

	// (PUT /api/settings)
	UpdateSettings(w http.ResponseWriter, r *http.Request)

	// (GET /api/writers)
	ListWriters(w http.ResponseWriter, r *http.Request)

	// (POST /api/writers)
	CreateWriter(w http.ResponseWriter, r *http.Request)
	// TestWriter Send a short sample request through the gateway
	// (POST /api/writers/test)
	TestWriter(w http.ResponseWriter, r *http.Request)

	// (DELETE /api/writers/{writerId})
	DeleteWriter(w http.ResponseWriter, r *http.Request, writerId WriterId)

	// (GET /api/writers/{writerId})
	GetWriter(w http.ResponseWriter, r *http.Request, writerId WriterId)

	// (PUT /api/writers/{writerId})
	UpdateWriter(w http.ResponseWriter, r *http.Request, writerId WriterId)

	// (POST /api/writers/{writerId}/duplicate)
	DuplicateWriter(w http.ResponseWriter, r *http.Request, writerId WriterId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (DELETE /api/bible-entries/{entryId})
func (_ Unimplemented) DeleteBibleEntry(w http.ResponseWriter, r *http.Request, entryId EntryId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /api/bible-entries/{entryId})
func (_ Unimplemented) UpdateBibleEntry(w http.ResponseWriter, r *http.Request, entryId EntryId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /api/chapters/{chapterId})
func (_ Unimplemented) DeleteChapter(w http.ResponseWriter, r *http.Request, chapterId ChapterId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/chapters/{chapterId})
func (_ Unimplemented) GetChapter(w http.ResponseWriter, r *http.Request, chapterId ChapterId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateChapter Rename or move a chapter
// (PUT /api/chapters/{chapterId})
func (_ Unimplemented) UpdateChapter(w http.ResponseWriter, r *http.Request, chapterId ChapterId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SaveChapterContent Save the chapter text; may create an autosave snapshot
// (PUT /api/chapters/{chapterId}/content)
func (_ Unimplemented) SaveChapterContent(w http.ResponseWriter, r *http.Request, chapterId ChapterId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// StartCritique Convene the Guild on a chapter
// (POST /api/chapters/{chapterId}/critiques)
func (_ Unimplemented) StartCritique(w http.ResponseWriter, r *http.Request, chapterId ChapterId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListChapterRuns Runs of a chapter, newest first
// (GET /api/chapters/{chapterId}/runs)
func (_ Unimplemented) ListChapterRuns(w http.ResponseWriter, r *http.Request, chapterId ChapterId, params ListChapterRunsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/chapters/{chapterId}/versions)
func (_ Unimplemented) ListChapterVersions(w http.ResponseWriter, r *http.Request, chapterId ChapterId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateChapterSnapshot Take a labelled snapshot by hand
// (POST /api/chapters/{chapterId}/versions)
func (_ Unimplemented) CreateChapterSnapshot(w http.ResponseWriter, r *http.Request, chapterId ChapterId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/chapters/{chapterId}/versions/{versionId})
func (_ Unimplemented) GetChapterVersion(w http.ResponseWriter, r *http.Request, chapterId ChapterId, versionId VersionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RestoreChapterVersion Snapshot the current text, then replace it with the version
// (POST /api/chapters/{chapterId}/versions/{versionId}/restore)
func (_ Unimplemented) RestoreChapterVersion(w http.ResponseWriter, r *http.Request, chapterId ChapterId, versionId VersionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListGatewayModels Aliases known to the gateway
// (GET /api/gateway/models)
func (_ Unimplemented) ListGatewayModels(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetMe Current account and app configuration
// (GET /api/me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/projects)
func (_ Unimplemented) ListProjects(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/projects)
func (_ Unimplemented) CreateProject(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /api/projects/{projectId})
func (_ Unimplemented) DeleteProject(w http.ResponseWriter, r *http.Request, projectId ProjectId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/projects/{projectId})
func (_ Unimplemented) GetProject(w http.ResponseWriter, r *http.Request, projectId ProjectId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /api/projects/{projectId})
func (_ Unimplemented) UpdateProject(w http.ResponseWriter, r *http.Request, projectId ProjectId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/projects/{projectId}/bible)
func (_ Unimplemented) ListBibleEntries(w http.ResponseWriter, r *http.Request, projectId ProjectId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/projects/{projectId}/bible)
func (_ Unimplemented) CreateBibleEntry(w http.ResponseWriter, r *http.Request, projectId ProjectId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/projects/{projectId}/chapters)
func (_ Unimplemented) ListChapters(w http.ResponseWriter, r *http.Request, projectId ProjectId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/projects/{projectId}/chapters)
func (_ Unimplemented) CreateChapter(w http.ResponseWriter, r *http.Request, projectId ProjectId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/runs/{runId})
func (_ Unimplemented) GetRun(w http.ResponseWriter, r *http.Request, runId RunId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CancelRun Stop a running run; a finished run is returned unchanged
// (POST /api/runs/{runId}/cancel)
func (_ Unimplemented) CancelRun(w http.ResponseWriter, r *http.Request, runId RunId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListRunCritiques The critics' validated replies for a critique run
// (GET /api/runs/{runId}/critiques)
func (_ Unimplemented) ListRunCritiques(w http.ResponseWriter, r *http.Request, runId RunId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// StreamRunEvents Follow a run as Server-Sent Events
// (GET /api/runs/{runId}/events)
func (_ Unimplemented) StreamRunEvents(w http.ResponseWriter, r *http.Request, runId RunId, params StreamRunEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListRunIssues The editor-in-chief's prioritized issue list for a critique run
// (GET /api/runs/{runId}/issues)
func (_ Unimplemented) ListRunIssues(w http.ResponseWriter, r *http.Request, runId RunId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/settings)
func (_ Unimplemented) GetSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /api/settings)
func (_ Unimplemented) UpdateSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/writers)
func (_ Unimplemented) ListWriters(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/writers)
func (_ Unimplemented) CreateWriter(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// TestWriter Send a short sample request through the gateway
// (POST /api/writers/test)
func (_ Unimplemented) TestWriter(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /api/writers/{writerId})
func (_ Unimplemented) DeleteWriter(w http.ResponseWriter, r *http.Request, writerId WriterId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/writers/{writerId})
func (_ Unimplemented) GetWriter(w http.ResponseWriter, r *http.Request, writerId WriterId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /api/writers/{writerId})
func (_ Unimplemented) UpdateWriter(w http.ResponseWriter, r *http.Request, writerId WriterId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/writers/{writerId}/duplicate)
func (_ Unimplemented) DuplicateWriter(w http.ResponseWriter, r *http.Request, writerId WriterId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DeleteBibleEntry operation middleware
func (siw *ServerInterfaceWrapper) DeleteBibleEntry(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "entryId" -------------
	var entryId EntryId

	err = runtime.BindStyledParameterWithOptions("simple", "entryId", chi.URLParam(r, "entryId"), &entryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entryId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteBibleEntry(w, r, entryId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateBibleEntry operation middleware
func (siw *ServerInterfaceWrapper) UpdateBibleEntry(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "entryId" -------------
	var entryId EntryId

	err = runtime.BindStyledParameterWithOptions("simple", "entryId", chi.URLParam(r, "entryId"), &entryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entryId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateBibleEntry(w, r, entryId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteChapter operation middleware
func (siw *ServerInterfaceWrapper) DeleteChapter(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "chapterId" -------------
	var chapterId ChapterId

	err = runtime.BindStyledParameterWithOptions("simple", "chapterId", chi.URLParam(r, "chapterId"), &chapterId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chapterId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteChapter(w, r, chapterId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetChapter operation middleware
func (siw *ServerInterfaceWrapper) GetChapter(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "chapterId" -------------
	var chapterId ChapterId

	err = runtime.BindStyledParameterWithOptions("simple", "chapterId", chi.URLParam(r, "chapterId"), &chapterId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chapterId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChapter(w, r, chapterId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateChapter operation middleware
func (siw *ServerInterfaceWrapper) UpdateChapter(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "chapterId" -------------
	var chapterId ChapterId

	err = runtime.BindStyledParameterWithOptions("simple", "chapterId", chi.URLParam(r, "chapterId"), &chapterId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chapterId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateChapter(w, r, chapterId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SaveChapterContent operation middleware
func (siw *ServerInterfaceWrapper) SaveChapterContent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "chapterId" -------------
	var chapterId ChapterId

	err = runtime.BindStyledParameterWithOptions("simple", "chapterId", chi.URLParam(r, "chapterId"), &chapterId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chapterId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SaveChapterContent(w, r, chapterId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartCritique operation middleware
func (siw *ServerInterfaceWrapper) StartCritique(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "chapterId" -------------
	var chapterId ChapterId

	err = runtime.BindStyledParameterWithOptions("simple", "chapterId", chi.URLParam(r, "chapterId"), &chapterId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chapterId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartCritique(w, r, chapterId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListChapterRuns operation middleware
func (siw *ServerInterfaceWrapper) ListChapterRuns(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "chapterId" -------------
	var chapterId ChapterId

	err = runtime.BindStyledParameterWithOptions("simple", "chapterId", chi.URLParam(r, "chapterId"), &chapterId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chapterId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListChapterRunsParams

	// ------------- Optional query parameter "kind" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "kind", r.URL.Query(), &params.Kind, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "kind"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "kind", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListChapterRuns(w, r, chapterId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListChapterVersions operation middleware
func (siw *ServerInterfaceWrapper) ListChapterVersions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "chapterId" -------------
	var chapterId ChapterId

	err = runtime.BindStyledParameterWithOptions("simple", "chapterId", chi.URLParam(r, "chapterId"), &chapterId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chapterId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListChapterVersions(w, r, chapterId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateChapterSnapshot operation middleware
func (siw *ServerInterfaceWrapper) CreateChapterSnapshot(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "chapterId" -------------
	var chapterId ChapterId

	err = runtime.BindStyledParameterWithOptions("simple", "chapterId", chi.URLParam(r, "chapterId"), &chapterId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chapterId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateChapterSnapshot(w, r, chapterId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetChapterVersion operation middleware
func (siw *ServerInterfaceWrapper) GetChapterVersion(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "chapterId" -------------
	var chapterId ChapterId

	err = runtime.BindStyledParameterWithOptions("simple", "chapterId", chi.URLParam(r, "chapterId"), &chapterId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chapterId", Err: err})
		return
	}

	// ------------- Path parameter "versionId" -------------
	var versionId VersionId

	err = runtime.BindStyledParameterWithOptions("simple", "versionId", chi.URLParam(r, "versionId"), &versionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "versionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChapterVersion(w, r, chapterId, versionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RestoreChapterVersion operation middleware
func (siw *ServerInterfaceWrapper) RestoreChapterVersion(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "chapterId" -------------
	var chapterId ChapterId

	err = runtime.BindStyledParameterWithOptions("simple", "chapterId", chi.URLParam(r, "chapterId"), &chapterId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chapterId", Err: err})
		return
	}

	// ------------- Path parameter "versionId" -------------
	var versionId VersionId

	err = runtime.BindStyledParameterWithOptions("simple", "versionId", chi.URLParam(r, "versionId"), &versionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "versionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RestoreChapterVersion(w, r, chapterId, versionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGatewayModels operation middleware
func (siw *ServerInterfaceWrapper) ListGatewayModels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGatewayModels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjects operation middleware
func (siw *ServerInterfaceWrapper) ListProjects(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjects(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProject operation middleware
func (siw *ServerInterfaceWrapper) CreateProject(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProject(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteProject operation middleware
func (siw *ServerInterfaceWrapper) DeleteProject(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteProject(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProject operation middleware
func (siw *ServerInterfaceWrapper) GetProject(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProject(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProject operation middleware
func (siw *ServerInterfaceWrapper) UpdateProject(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProject(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListBibleEntries operation middleware
func (siw *ServerInterfaceWrapper) ListBibleEntries(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBibleEntries(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateBibleEntry operation middleware
func (siw *ServerInterfaceWrapper) CreateBibleEntry(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateBibleEntry(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListChapters operation middleware
func (siw *ServerInterfaceWrapper) ListChapters(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListChapters(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateChapter operation middleware
func (siw *ServerInterfaceWrapper) CreateChapter(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateChapter(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRun operation middleware
func (siw *ServerInterfaceWrapper) GetRun(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRun(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelRun operation middleware
func (siw *ServerInterfaceWrapper) CancelRun(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelRun(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRunCritiques operation middleware
func (siw *ServerInterfaceWrapper) ListRunCritiques(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRunCritiques(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamRunEvents operation middleware
func (siw *ServerInterfaceWrapper) StreamRunEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params StreamRunEventsParams

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "after", r.URL.Query(), &params.After, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "after"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamRunEvents(w, r, runId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRunIssues operation middleware
func (siw *ServerInterfaceWrapper) ListRunIssues(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRunIssues(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSettings operation middleware
func (siw *ServerInterfaceWrapper) GetSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSettings operation middleware
func (siw *ServerInterfaceWrapper) UpdateSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWriters operation middleware
func (siw *ServerInterfaceWrapper) ListWriters(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWriters(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateWriter operation middleware
func (siw *ServerInterfaceWrapper) CreateWriter(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateWriter(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TestWriter operation middleware
func (siw *ServerInterfaceWrapper) TestWriter(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TestWriter(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteWriter operation middleware
func (siw *ServerInterfaceWrapper) DeleteWriter(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "writerId" -------------
	var writerId WriterId

	err = runtime.BindStyledParameterWithOptions("simple", "writerId", chi.URLParam(r, "writerId"), &writerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "writerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteWriter(w, r, writerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWriter operation middleware
func (siw *ServerInterfaceWrapper) GetWriter(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "writerId" -------------
	var writerId WriterId

	err = runtime.BindStyledParameterWithOptions("simple", "writerId", chi.URLParam(r, "writerId"), &writerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "writerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWriter(w, r, writerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateWriter operation middleware
func (siw *ServerInterfaceWrapper) UpdateWriter(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "writerId" -------------
	var writerId WriterId

	err = runtime.BindStyledParameterWithOptions("simple", "writerId", chi.URLParam(r, "writerId"), &writerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "writerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateWriter(w, r, writerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DuplicateWriter operation middleware
func (siw *ServerInterfaceWrapper) DuplicateWriter(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "writerId" -------------
	var writerId WriterId

	err = runtime.BindStyledParameterWithOptions("simple", "writerId", chi.URLParam(r, "writerId"), &writerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "writerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DuplicateWriter(w, r, writerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/me", wrapper.GetMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/settings", wrapper.GetSettings)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/settings", wrapper.UpdateSettings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/gateway/models", wrapper.ListGatewayModels)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/projects", wrapper.ListProjects)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/projects", wrapper.CreateProject)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/projects/{projectId}", wrapper.DeleteProject)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/projects/{projectId}", wrapper.GetProject)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/projects/{projectId}", wrapper.UpdateProject)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/projects/{projectId}/chapters", wrapper.ListChapters)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/projects/{projectId}/chapters", wrapper.CreateChapter)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/projects/{projectId}/bible", wrapper.ListBibleEntries)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/projects/{projectId}/bible", wrapper.CreateBibleEntry)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/bible-entries/{entryId}", wrapper.DeleteBibleEntry)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/bible-entries/{entryId}", wrapper.UpdateBibleEntry)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/chapters/{chapterId}", wrapper.DeleteChapter)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/chapters/{chapterId}", wrapper.GetChapter)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/chapters/{chapterId}", wrapper.UpdateChapter)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/chapters/{chapterId}/content", wrapper.SaveChapterContent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/chapters/{chapterId}/versions", wrapper.ListChapterVersions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/chapters/{chapterId}/versions", wrapper.CreateChapterSnapshot)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/chapters/{chapterId}/versions/{versionId}", wrapper.GetChapterVersion)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/chapters/{chapterId}/versions/{versionId}/restore", wrapper.RestoreChapterVersion)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/chapters/{chapterId}/runs", wrapper.ListChapterRuns)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/chapters/{chapterId}/critiques", wrapper.StartCritique)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/runs/{runId}/critiques", wrapper.ListRunCritiques)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/runs/{runId}/issues", wrapper.ListRunIssues)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/runs/{runId}", wrapper.GetRun)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/runs/{runId}/cancel", wrapper.CancelRun)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/runs/{runId}/events", wrapper.StreamRunEvents)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/writers", wrapper.ListWriters)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/writers", wrapper.CreateWriter)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/writers/test", wrapper.TestWriter)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/writers/{writerId}", wrapper.DeleteWriter)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/writers/{writerId}", wrapper.GetWriter)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/writers/{writerId}", wrapper.UpdateWriter)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/writers/{writerId}/duplicate", wrapper.DuplicateWriter)
	})

	return r
}
