// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bible.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createBibleEntry = `-- name: CreateBibleEntry :one
INSERT INTO bible_entries (user_id, project_id, section, title, fields, chapter_id, position)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, project_id, section, title, fields, chapter_id, position, created_at, updated_at
`

type CreateBibleEntryParams struct {
	UserID    uuid.UUID
	ProjectID uuid.UUID
	Section   string
	Title     string
	Fields    []byte
	ChapterID uuid.NullUUID
	Position  int32
}

func (q *Queries) CreateBibleEntry(ctx context.Context, arg CreateBibleEntryParams) (BibleEntry, error) {
	row := q.db.QueryRow(ctx, createBibleEntry,
		arg.UserID,
		arg.ProjectID,
		arg.Section,
		arg.Title,
		arg.Fields,
		arg.ChapterID,
		arg.Position,
	)
	var i BibleEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Section,
		&i.Title,
		&i.Fields,
		&i.ChapterID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBibleEntry = `-- name: DeleteBibleEntry :execrows
DELETE FROM bible_entries WHERE id = $1 AND user_id = $2
`

type DeleteBibleEntryParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteBibleEntry(ctx context.Context, arg DeleteBibleEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBibleEntry, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBibleEntry = `-- name: GetBibleEntry :one
SELECT id, user_id, project_id, section, title, fields, chapter_id, position, created_at, updated_at FROM bible_entries WHERE id = $1 AND user_id = $2
`

type GetBibleEntryParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetBibleEntry(ctx context.Context, arg GetBibleEntryParams) (BibleEntry, error) {
	row := q.db.QueryRow(ctx, getBibleEntry, arg.ID, arg.UserID)
	var i BibleEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Section,
		&i.Title,
		&i.Fields,
		&i.ChapterID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBibleEntries = `-- name: ListBibleEntries :many
SELECT id, user_id, project_id, section, title, fields, chapter_id, position, created_at, updated_at FROM bible_entries
WHERE project_id = $1 AND user_id = $2
ORDER BY section, position, created_at
`

type ListBibleEntriesParams struct {
	ProjectID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) ListBibleEntries(ctx context.Context, arg ListBibleEntriesParams) ([]BibleEntry, error) {
	rows, err := q.db.Query(ctx, listBibleEntries, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BibleEntry{}
	for rows.Next() {
		var i BibleEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Section,
			&i.Title,
			&i.Fields,
			&i.ChapterID,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextBibleEntryPosition = `-- name: NextBibleEntryPosition :one
SELECT (coalesce(max(position), -1) + 1)::integer FROM bible_entries WHERE project_id = $1 AND section = $2
`

type NextBibleEntryPositionParams struct {
	ProjectID uuid.UUID
	Section   string
}

func (q *Queries) NextBibleEntryPosition(ctx context.Context, arg NextBibleEntryPositionParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextBibleEntryPosition, arg.ProjectID, arg.Section)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const updateBibleEntry = `-- name: UpdateBibleEntry :one
UPDATE bible_entries SET title = $3, fields = $4, chapter_id = $5, position = $6, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, project_id, section, title, fields, chapter_id, position, created_at, updated_at
`

type UpdateBibleEntryParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Title     string
	Fields    []byte
	ChapterID uuid.NullUUID
	Position  int32
}

func (q *Queries) UpdateBibleEntry(ctx context.Context, arg UpdateBibleEntryParams) (BibleEntry, error) {
	row := q.db.QueryRow(ctx, updateBibleEntry,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Fields,
		arg.ChapterID,
		arg.Position,
	)
	var i BibleEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Section,
		&i.Title,
		&i.Fields,
		&i.ChapterID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
