// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bible_proposals.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createBibleProposal = `-- name: CreateBibleProposal :one
INSERT INTO bible_proposals (user_id, run_id, project_id, chapter_id, revision_id, action, entry_id, section, title, fields, rationale, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, user_id, run_id, project_id, chapter_id, revision_id, action, entry_id, section, title, fields, rationale, status, applied_entry_id, position, created_at, decided_at
`

type CreateBibleProposalParams struct {
	UserID     uuid.UUID
	RunID      uuid.UUID
	ProjectID  uuid.UUID
	ChapterID  uuid.NullUUID
	RevisionID uuid.NullUUID
	Action     string
	EntryID    uuid.NullUUID
	Section    string
	Title      string
	Fields     []byte
	Rationale  string
	Position   int32
}

func (q *Queries) CreateBibleProposal(ctx context.Context, arg CreateBibleProposalParams) (BibleProposal, error) {
	row := q.db.QueryRow(ctx, createBibleProposal,
		arg.UserID,
		arg.RunID,
		arg.ProjectID,
		arg.ChapterID,
		arg.RevisionID,
		arg.Action,
		arg.EntryID,
		arg.Section,
		arg.Title,
		arg.Fields,
		arg.Rationale,
		arg.Position,
	)
	var i BibleProposal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RunID,
		&i.ProjectID,
		&i.ChapterID,
		&i.RevisionID,
		&i.Action,
		&i.EntryID,
		&i.Section,
		&i.Title,
		&i.Fields,
		&i.Rationale,
		&i.Status,
		&i.AppliedEntryID,
		&i.Position,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const decideBibleProposal = `-- name: DecideBibleProposal :one
UPDATE bible_proposals
SET status = $3, title = $4, fields = $5, applied_entry_id = $6, decided_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, run_id, project_id, chapter_id, revision_id, action, entry_id, section, title, fields, rationale, status, applied_entry_id, position, created_at, decided_at
`

type DecideBibleProposalParams struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Status         string
	Title          string
	Fields         []byte
	AppliedEntryID uuid.NullUUID
}

func (q *Queries) DecideBibleProposal(ctx context.Context, arg DecideBibleProposalParams) (BibleProposal, error) {
	row := q.db.QueryRow(ctx, decideBibleProposal,
		arg.ID,
		arg.UserID,
		arg.Status,
		arg.Title,
		arg.Fields,
		arg.AppliedEntryID,
	)
	var i BibleProposal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RunID,
		&i.ProjectID,
		&i.ChapterID,
		&i.RevisionID,
		&i.Action,
		&i.EntryID,
		&i.Section,
		&i.Title,
		&i.Fields,
		&i.Rationale,
		&i.Status,
		&i.AppliedEntryID,
		&i.Position,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const getBibleProposal = `-- name: GetBibleProposal :one
SELECT id, user_id, run_id, project_id, chapter_id, revision_id, action, entry_id, section, title, fields, rationale, status, applied_entry_id, position, created_at, decided_at FROM bible_proposals WHERE id = $1 AND user_id = $2
`

type GetBibleProposalParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetBibleProposal(ctx context.Context, arg GetBibleProposalParams) (BibleProposal, error) {
	row := q.db.QueryRow(ctx, getBibleProposal, arg.ID, arg.UserID)
	var i BibleProposal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RunID,
		&i.ProjectID,
		&i.ChapterID,
		&i.RevisionID,
		&i.Action,
		&i.EntryID,
		&i.Section,
		&i.Title,
		&i.Fields,
		&i.Rationale,
		&i.Status,
		&i.AppliedEntryID,
		&i.Position,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const getBibleProposalForUpdate = `-- name: GetBibleProposalForUpdate :one
SELECT id, user_id, run_id, project_id, chapter_id, revision_id, action, entry_id, section, title, fields, rationale, status, applied_entry_id, position, created_at, decided_at FROM bible_proposals WHERE id = $1 AND user_id = $2 FOR UPDATE
`

type GetBibleProposalForUpdateParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetBibleProposalForUpdate(ctx context.Context, arg GetBibleProposalForUpdateParams) (BibleProposal, error) {
	row := q.db.QueryRow(ctx, getBibleProposalForUpdate, arg.ID, arg.UserID)
	var i BibleProposal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RunID,
		&i.ProjectID,
		&i.ChapterID,
		&i.RevisionID,
		&i.Action,
		&i.EntryID,
		&i.Section,
		&i.Title,
		&i.Fields,
		&i.Rationale,
		&i.Status,
		&i.AppliedEntryID,
		&i.Position,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const listProjectBibleProposals = `-- name: ListProjectBibleProposals :many
SELECT id, user_id, run_id, project_id, chapter_id, revision_id, action, entry_id, section, title, fields, rationale, status, applied_entry_id, position, created_at, decided_at FROM bible_proposals
WHERE project_id = $1 AND user_id = $2 AND ($3::text = '' OR status = $3::text)
ORDER BY created_at DESC, position
LIMIT $4
`

type ListProjectBibleProposalsParams struct {
	ProjectID uuid.UUID
	UserID    uuid.UUID
	Status    string
	RowLimit  int32
}

func (q *Queries) ListProjectBibleProposals(ctx context.Context, arg ListProjectBibleProposalsParams) ([]BibleProposal, error) {
	rows, err := q.db.Query(ctx, listProjectBibleProposals,
		arg.ProjectID,
		arg.UserID,
		arg.Status,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BibleProposal{}
	for rows.Next() {
		var i BibleProposal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RunID,
			&i.ProjectID,
			&i.ChapterID,
			&i.RevisionID,
			&i.Action,
			&i.EntryID,
			&i.Section,
			&i.Title,
			&i.Fields,
			&i.Rationale,
			&i.Status,
			&i.AppliedEntryID,
			&i.Position,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunBibleProposals = `-- name: ListRunBibleProposals :many
SELECT id, user_id, run_id, project_id, chapter_id, revision_id, action, entry_id, section, title, fields, rationale, status, applied_entry_id, position, created_at, decided_at FROM bible_proposals WHERE run_id = $1 AND user_id = $2 ORDER BY position
`

type ListRunBibleProposalsParams struct {
	RunID  uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) ListRunBibleProposals(ctx context.Context, arg ListRunBibleProposalsParams) ([]BibleProposal, error) {
	rows, err := q.db.Query(ctx, listRunBibleProposals, arg.RunID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BibleProposal{}
	for rows.Next() {
		var i BibleProposal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RunID,
			&i.ProjectID,
			&i.ChapterID,
			&i.RevisionID,
			&i.Action,
			&i.EntryID,
			&i.Section,
			&i.Title,
			&i.Fields,
			&i.Rationale,
			&i.Status,
			&i.AppliedEntryID,
			&i.Position,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
