// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chapters.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createChapter = `-- name: CreateChapter :one
INSERT INTO chapters (user_id, project_id, title, position, content_md, content_hash)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, project_id, title, position, content_md, content_hash, created_at, updated_at
`

type CreateChapterParams struct {
	UserID      uuid.UUID
	ProjectID   uuid.UUID
	Title       string
	Position    int32
	ContentMd   string
	ContentHash string
}

func (q *Queries) CreateChapter(ctx context.Context, arg CreateChapterParams) (Chapter, error) {
	row := q.db.QueryRow(ctx, createChapter,
		arg.UserID,
		arg.ProjectID,
		arg.Title,
		arg.Position,
		arg.ContentMd,
		arg.ContentHash,
	)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.Position,
		&i.ContentMd,
		&i.ContentHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChapter = `-- name: DeleteChapter :execrows
DELETE FROM chapters WHERE id = $1 AND user_id = $2
`

type DeleteChapterParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteChapter(ctx context.Context, arg DeleteChapterParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChapter, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChapter = `-- name: GetChapter :one
SELECT id, user_id, project_id, title, position, content_md, content_hash, created_at, updated_at FROM chapters WHERE id = $1 AND user_id = $2
`

type GetChapterParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetChapter(ctx context.Context, arg GetChapterParams) (Chapter, error) {
	row := q.db.QueryRow(ctx, getChapter, arg.ID, arg.UserID)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.Position,
		&i.ContentMd,
		&i.ContentHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChapterForUpdate = `-- name: GetChapterForUpdate :one
SELECT id, user_id, project_id, title, position, content_md, content_hash, created_at, updated_at FROM chapters WHERE id = $1 AND user_id = $2 FOR UPDATE
`

type GetChapterForUpdateParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetChapterForUpdate(ctx context.Context, arg GetChapterForUpdateParams) (Chapter, error) {
	row := q.db.QueryRow(ctx, getChapterForUpdate, arg.ID, arg.UserID)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.Position,
		&i.ContentMd,
		&i.ContentHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChapters = `-- name: ListChapters :many
SELECT id, user_id, project_id, title, position, content_hash, created_at, updated_at,
       length(content_md)::integer AS content_length
FROM chapters
WHERE project_id = $1 AND user_id = $2
ORDER BY position, created_at
`

type ListChaptersParams struct {
	ProjectID uuid.UUID
	UserID    uuid.UUID
}

type ListChaptersRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	ProjectID     uuid.UUID
	Title         string
	Position      int32
	ContentHash   string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ContentLength int32
}

func (q *Queries) ListChapters(ctx context.Context, arg ListChaptersParams) ([]ListChaptersRow, error) {
	rows, err := q.db.Query(ctx, listChapters, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChaptersRow{}
	for rows.Next() {
		var i ListChaptersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.Position,
			&i.ContentHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentLength,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextChapterPosition = `-- name: NextChapterPosition :one
SELECT (coalesce(max(position), -1) + 1)::integer FROM chapters WHERE project_id = $1
`

func (q *Queries) NextChapterPosition(ctx context.Context, projectID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextChapterPosition, projectID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const updateChapterContent = `-- name: UpdateChapterContent :one
UPDATE chapters SET content_md = $3, content_hash = $4, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, project_id, title, position, content_md, content_hash, created_at, updated_at
`

type UpdateChapterContentParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	ContentMd   string
	ContentHash string
}

func (q *Queries) UpdateChapterContent(ctx context.Context, arg UpdateChapterContentParams) (Chapter, error) {
	row := q.db.QueryRow(ctx, updateChapterContent,
		arg.ID,
		arg.UserID,
		arg.ContentMd,
		arg.ContentHash,
	)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.Position,
		&i.ContentMd,
		&i.ContentHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateChapterMeta = `-- name: UpdateChapterMeta :one
UPDATE chapters SET title = $3, position = $4, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, project_id, title, position, content_md, content_hash, created_at, updated_at
`

type UpdateChapterMetaParams struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	Title    string
	Position int32
}

func (q *Queries) UpdateChapterMeta(ctx context.Context, arg UpdateChapterMetaParams) (Chapter, error) {
	row := q.db.QueryRow(ctx, updateChapterMeta,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Position,
	)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.Position,
		&i.ContentMd,
		&i.ContentHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
