// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: critiques.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createCritique = `-- name: CreateCritique :one
INSERT INTO critiques (user_id, run_id, chapter_id, writer_id, writer_name, writer_slug, model_alias, status, scene_count)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'running', $8)
RETURNING id, user_id, run_id, chapter_id, writer_id, writer_name, writer_slug, model_alias, status, raw_text, critique, error, scene_count, prompt_tokens, completion_tokens, cost_usd, cost_estimated, created_at, finished_at
`

type CreateCritiqueParams struct {
	UserID     uuid.UUID
	RunID      uuid.UUID
	ChapterID  uuid.NullUUID
	WriterID   uuid.NullUUID
	WriterName string
	WriterSlug string
	ModelAlias string
	SceneCount int32
}

func (q *Queries) CreateCritique(ctx context.Context, arg CreateCritiqueParams) (Critique, error) {
	row := q.db.QueryRow(ctx, createCritique,
		arg.UserID,
		arg.RunID,
		arg.ChapterID,
		arg.WriterID,
		arg.WriterName,
		arg.WriterSlug,
		arg.ModelAlias,
		arg.SceneCount,
	)
	var i Critique
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RunID,
		&i.ChapterID,
		&i.WriterID,
		&i.WriterName,
		&i.WriterSlug,
		&i.ModelAlias,
		&i.Status,
		&i.RawText,
		&i.Critique,
		&i.Error,
		&i.SceneCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CostUsd,
		&i.CostEstimated,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishCritique = `-- name: FinishCritique :one
UPDATE critiques
SET status = $2, raw_text = $3, critique = $4, error = $5,
    prompt_tokens = $6, completion_tokens = $7, cost_usd = $8, cost_estimated = $9,
    finished_at = now()
WHERE id = $1
RETURNING id, user_id, run_id, chapter_id, writer_id, writer_name, writer_slug, model_alias, status, raw_text, critique, error, scene_count, prompt_tokens, completion_tokens, cost_usd, cost_estimated, created_at, finished_at
`

type FinishCritiqueParams struct {
	ID               uuid.UUID
	Status           string
	RawText          string
	Critique         []byte
	Error            string
	PromptTokens     int32
	CompletionTokens int32
	CostUsd          float64
	CostEstimated    bool
}

func (q *Queries) FinishCritique(ctx context.Context, arg FinishCritiqueParams) (Critique, error) {
	row := q.db.QueryRow(ctx, finishCritique,
		arg.ID,
		arg.Status,
		arg.RawText,
		arg.Critique,
		arg.Error,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.CostUsd,
		arg.CostEstimated,
	)
	var i Critique
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RunID,
		&i.ChapterID,
		&i.WriterID,
		&i.WriterName,
		&i.WriterSlug,
		&i.ModelAlias,
		&i.Status,
		&i.RawText,
		&i.Critique,
		&i.Error,
		&i.SceneCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CostUsd,
		&i.CostEstimated,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getCritique = `-- name: GetCritique :one
SELECT id, user_id, run_id, chapter_id, writer_id, writer_name, writer_slug, model_alias, status, raw_text, critique, error, scene_count, prompt_tokens, completion_tokens, cost_usd, cost_estimated, created_at, finished_at FROM critiques WHERE id = $1 AND user_id = $2
`

type GetCritiqueParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetCritique(ctx context.Context, arg GetCritiqueParams) (Critique, error) {
	row := q.db.QueryRow(ctx, getCritique, arg.ID, arg.UserID)
	var i Critique
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RunID,
		&i.ChapterID,
		&i.WriterID,
		&i.WriterName,
		&i.WriterSlug,
		&i.ModelAlias,
		&i.Status,
		&i.RawText,
		&i.Critique,
		&i.Error,
		&i.SceneCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CostUsd,
		&i.CostEstimated,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listRunCritiques = `-- name: ListRunCritiques :many
SELECT id, user_id, run_id, chapter_id, writer_id, writer_name, writer_slug, model_alias, status, raw_text, critique, error, scene_count, prompt_tokens, completion_tokens, cost_usd, cost_estimated, created_at, finished_at FROM critiques WHERE run_id = $1 AND user_id = $2 ORDER BY created_at, writer_name
`

type ListRunCritiquesParams struct {
	RunID  uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) ListRunCritiques(ctx context.Context, arg ListRunCritiquesParams) ([]Critique, error) {
	rows, err := q.db.Query(ctx, listRunCritiques, arg.RunID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Critique{}
	for rows.Next() {
		var i Critique
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RunID,
			&i.ChapterID,
			&i.WriterID,
			&i.WriterName,
			&i.WriterSlug,
			&i.ModelAlias,
			&i.Status,
			&i.RawText,
			&i.Critique,
			&i.Error,
			&i.SceneCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.CostUsd,
			&i.CostEstimated,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
