// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drafts.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createDraft = `-- name: CreateDraft :one
INSERT INTO drafts (user_id, run_id, chapter_id, writer_id, writer_name, writer_slug, model_alias, mode, instruction, selection, notes,
                    context_before, context_after, content_hash, status, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, 'running', $15)
RETURNING id, user_id, run_id, chapter_id, writer_id, writer_name, writer_slug, model_alias, mode, instruction, selection, notes, context_before, context_after, content_hash, status, text, error, decision, decided_at, position, prompt_tokens, completion_tokens, cost_usd, cost_estimated, created_at, finished_at
`

type CreateDraftParams struct {
	UserID        uuid.UUID
	RunID         uuid.UUID
	ChapterID     uuid.NullUUID
	WriterID      uuid.NullUUID
	WriterName    string
	WriterSlug    string
	ModelAlias    string
	Mode          string
	Instruction   string
	Selection     string
	Notes         string
	ContextBefore string
	ContextAfter  string
	ContentHash   string
	Position      int32
}

func (q *Queries) CreateDraft(ctx context.Context, arg CreateDraftParams) (Draft, error) {
	row := q.db.QueryRow(ctx, createDraft,
		arg.UserID,
		arg.RunID,
		arg.ChapterID,
		arg.WriterID,
		arg.WriterName,
		arg.WriterSlug,
		arg.ModelAlias,
		arg.Mode,
		arg.Instruction,
		arg.Selection,
		arg.Notes,
		arg.ContextBefore,
		arg.ContextAfter,
		arg.ContentHash,
		arg.Position,
	)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RunID,
		&i.ChapterID,
		&i.WriterID,
		&i.WriterName,
		&i.WriterSlug,
		&i.ModelAlias,
		&i.Mode,
		&i.Instruction,
		&i.Selection,
		&i.Notes,
		&i.ContextBefore,
		&i.ContextAfter,
		&i.ContentHash,
		&i.Status,
		&i.Text,
		&i.Error,
		&i.Decision,
		&i.DecidedAt,
		&i.Position,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CostUsd,
		&i.CostEstimated,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishDraft = `-- name: FinishDraft :one
UPDATE drafts
SET status = $2, text = $3, error = $4, prompt_tokens = $5, completion_tokens = $6, cost_usd = $7, cost_estimated = $8, finished_at = now()
WHERE id = $1
RETURNING id, user_id, run_id, chapter_id, writer_id, writer_name, writer_slug, model_alias, mode, instruction, selection, notes, context_before, context_after, content_hash, status, text, error, decision, decided_at, position, prompt_tokens, completion_tokens, cost_usd, cost_estimated, created_at, finished_at
`

type FinishDraftParams struct {
	ID               uuid.UUID
	Status           string
	Text             string
	Error            string
	PromptTokens     int32
	CompletionTokens int32
	CostUsd          float64
	CostEstimated    bool
}

func (q *Queries) FinishDraft(ctx context.Context, arg FinishDraftParams) (Draft, error) {
	row := q.db.QueryRow(ctx, finishDraft,
		arg.ID,
		arg.Status,
		arg.Text,
		arg.Error,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.CostUsd,
		arg.CostEstimated,
	)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RunID,
		&i.ChapterID,
		&i.WriterID,
		&i.WriterName,
		&i.WriterSlug,
		&i.ModelAlias,
		&i.Mode,
		&i.Instruction,
		&i.Selection,
		&i.Notes,
		&i.ContextBefore,
		&i.ContextAfter,
		&i.ContentHash,
		&i.Status,
		&i.Text,
		&i.Error,
		&i.Decision,
		&i.DecidedAt,
		&i.Position,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CostUsd,
		&i.CostEstimated,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getDraft = `-- name: GetDraft :one
SELECT id, user_id, run_id, chapter_id, writer_id, writer_name, writer_slug, model_alias, mode, instruction, selection, notes, context_before, context_after, content_hash, status, text, error, decision, decided_at, position, prompt_tokens, completion_tokens, cost_usd, cost_estimated, created_at, finished_at FROM drafts WHERE id = $1 AND user_id = $2
`

type GetDraftParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetDraft(ctx context.Context, arg GetDraftParams) (Draft, error) {
	row := q.db.QueryRow(ctx, getDraft, arg.ID, arg.UserID)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RunID,
		&i.ChapterID,
		&i.WriterID,
		&i.WriterName,
		&i.WriterSlug,
		&i.ModelAlias,
		&i.Mode,
		&i.Instruction,
		&i.Selection,
		&i.Notes,
		&i.ContextBefore,
		&i.ContextAfter,
		&i.ContentHash,
		&i.Status,
		&i.Text,
		&i.Error,
		&i.Decision,
		&i.DecidedAt,
		&i.Position,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CostUsd,
		&i.CostEstimated,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listChapterDrafts = `-- name: ListChapterDrafts :many
SELECT id, user_id, run_id, chapter_id, writer_id, writer_name, writer_slug, model_alias, mode, instruction, selection, notes, context_before, context_after, content_hash, status, text, error, decision, decided_at, position, prompt_tokens, completion_tokens, cost_usd, cost_estimated, created_at, finished_at FROM drafts WHERE chapter_id = $1 AND user_id = $2 ORDER BY created_at DESC, position LIMIT $3
`

type ListChapterDraftsParams struct {
	ChapterID uuid.NullUUID
	UserID    uuid.UUID
	RowLimit  int32
}

func (q *Queries) ListChapterDrafts(ctx context.Context, arg ListChapterDraftsParams) ([]Draft, error) {
	rows, err := q.db.Query(ctx, listChapterDrafts, arg.ChapterID, arg.UserID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Draft{}
	for rows.Next() {
		var i Draft
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RunID,
			&i.ChapterID,
			&i.WriterID,
			&i.WriterName,
			&i.WriterSlug,
			&i.ModelAlias,
			&i.Mode,
			&i.Instruction,
			&i.Selection,
			&i.Notes,
			&i.ContextBefore,
			&i.ContextAfter,
			&i.ContentHash,
			&i.Status,
			&i.Text,
			&i.Error,
			&i.Decision,
			&i.DecidedAt,
			&i.Position,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.CostUsd,
			&i.CostEstimated,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunDrafts = `-- name: ListRunDrafts :many
SELECT id, user_id, run_id, chapter_id, writer_id, writer_name, writer_slug, model_alias, mode, instruction, selection, notes, context_before, context_after, content_hash, status, text, error, decision, decided_at, position, prompt_tokens, completion_tokens, cost_usd, cost_estimated, created_at, finished_at FROM drafts WHERE run_id = $1 AND user_id = $2 ORDER BY position
`

type ListRunDraftsParams struct {
	RunID  uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) ListRunDrafts(ctx context.Context, arg ListRunDraftsParams) ([]Draft, error) {
	rows, err := q.db.Query(ctx, listRunDrafts, arg.RunID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Draft{}
	for rows.Next() {
		var i Draft
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RunID,
			&i.ChapterID,
			&i.WriterID,
			&i.WriterName,
			&i.WriterSlug,
			&i.ModelAlias,
			&i.Mode,
			&i.Instruction,
			&i.Selection,
			&i.Notes,
			&i.ContextBefore,
			&i.ContextAfter,
			&i.ContentHash,
			&i.Status,
			&i.Text,
			&i.Error,
			&i.Decision,
			&i.DecidedAt,
			&i.Position,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.CostUsd,
			&i.CostEstimated,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDraftDecision = `-- name: SetDraftDecision :one
UPDATE drafts SET decision = $3, decided_at = CASE WHEN $3 = 'pending' THEN NULL ELSE now() END
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, run_id, chapter_id, writer_id, writer_name, writer_slug, model_alias, mode, instruction, selection, notes, context_before, context_after, content_hash, status, text, error, decision, decided_at, position, prompt_tokens, completion_tokens, cost_usd, cost_estimated, created_at, finished_at
`

type SetDraftDecisionParams struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	Decision string
}

func (q *Queries) SetDraftDecision(ctx context.Context, arg SetDraftDecisionParams) (Draft, error) {
	row := q.db.QueryRow(ctx, setDraftDecision, arg.ID, arg.UserID, arg.Decision)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RunID,
		&i.ChapterID,
		&i.WriterID,
		&i.WriterName,
		&i.WriterSlug,
		&i.ModelAlias,
		&i.Mode,
		&i.Instruction,
		&i.Selection,
		&i.Notes,
		&i.ContextBefore,
		&i.ContextAfter,
		&i.ContentHash,
		&i.Status,
		&i.Text,
		&i.Error,
		&i.Decision,
		&i.DecidedAt,
		&i.Position,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CostUsd,
		&i.CostEstimated,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}
