// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: history.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const chapterRunKindCounts = `-- name: ChapterRunKindCounts :many
SELECT kind, count(*)::integer AS count FROM runs WHERE chapter_id = $1 AND user_id = $2 GROUP BY kind ORDER BY kind
`

type ChapterRunKindCountsParams struct {
	ChapterID uuid.NullUUID
	UserID    uuid.UUID
}

type ChapterRunKindCountsRow struct {
	Kind  string
	Count int32
}

func (q *Queries) ChapterRunKindCounts(ctx context.Context, arg ChapterRunKindCountsParams) ([]ChapterRunKindCountsRow, error) {
	rows, err := q.db.Query(ctx, chapterRunKindCounts, arg.ChapterID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChapterRunKindCountsRow{}
	for rows.Next() {
		var i ChapterRunKindCountsRow
		if err := rows.Scan(&i.Kind, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const chapterRunTotals = `-- name: ChapterRunTotals :one
SELECT count(*)::integer AS runs,
       coalesce(sum(cost_usd), 0)::double precision AS cost_usd,
       coalesce(bool_or(cost_estimated), false)::boolean AS cost_estimated,
       coalesce(sum(prompt_tokens), 0)::bigint AS prompt_tokens,
       coalesce(sum(completion_tokens), 0)::bigint AS completion_tokens
FROM runs
WHERE chapter_id = $1 AND user_id = $2 AND ($3::text = '' OR kind = $3::text)
`

type ChapterRunTotalsParams struct {
	ChapterID uuid.NullUUID
	UserID    uuid.UUID
	Kind      string
}

type ChapterRunTotalsRow struct {
	Runs             int32
	CostUsd          float64
	CostEstimated    bool
	PromptTokens     int64
	CompletionTokens int64
}

func (q *Queries) ChapterRunTotals(ctx context.Context, arg ChapterRunTotalsParams) (ChapterRunTotalsRow, error) {
	row := q.db.QueryRow(ctx, chapterRunTotals, arg.ChapterID, arg.UserID, arg.Kind)
	var i ChapterRunTotalsRow
	err := row.Scan(
		&i.Runs,
		&i.CostUsd,
		&i.CostEstimated,
		&i.PromptTokens,
		&i.CompletionTokens,
	)
	return i, err
}

const critiqueCountsByRun = `-- name: CritiqueCountsByRun :many
SELECT run_id, count(*)::integer AS critics, count(*) FILTER (WHERE status = 'failed')::integer AS failed
FROM critiques WHERE run_id = ANY($1::uuid[]) GROUP BY run_id
`

type CritiqueCountsByRunRow struct {
	RunID   uuid.UUID
	Critics int32
	Failed  int32
}

func (q *Queries) CritiqueCountsByRun(ctx context.Context, runIds []uuid.UUID) ([]CritiqueCountsByRunRow, error) {
	rows, err := q.db.Query(ctx, critiqueCountsByRun, runIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CritiqueCountsByRunRow{}
	for rows.Next() {
		var i CritiqueCountsByRunRow
		if err := rows.Scan(&i.RunID, &i.Critics, &i.Failed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const draftCountsByRun = `-- name: DraftCountsByRun :many
SELECT run_id, count(*)::integer AS count,
       count(*) FILTER (WHERE decision = 'inserted')::integer AS inserted,
       count(*) FILTER (WHERE decision = 'replaced')::integer AS replaced,
       count(*) FILTER (WHERE decision = 'discarded')::integer AS discarded,
       count(*) FILTER (WHERE decision = 'pending' AND status = 'succeeded')::integer AS pending
FROM drafts WHERE run_id = ANY($1::uuid[]) GROUP BY run_id
`

type DraftCountsByRunRow struct {
	RunID     uuid.UUID
	Count     int32
	Inserted  int32
	Replaced  int32
	Discarded int32
	Pending   int32
}

func (q *Queries) DraftCountsByRun(ctx context.Context, runIds []uuid.UUID) ([]DraftCountsByRunRow, error) {
	rows, err := q.db.Query(ctx, draftCountsByRun, runIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DraftCountsByRunRow{}
	for rows.Next() {
		var i DraftCountsByRunRow
		if err := rows.Scan(
			&i.RunID,
			&i.Count,
			&i.Inserted,
			&i.Replaced,
			&i.Discarded,
			&i.Pending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const issueCountsByRun = `-- name: IssueCountsByRun :many
SELECT run_id, count(*)::integer AS issues,
       count(*) FILTER (WHERE decision = 'accepted')::integer AS accepted,
       count(*) FILTER (WHERE decision = 'rejected')::integer AS rejected,
       count(*) FILTER (WHERE decision = 'pending')::integer AS pending
FROM issues WHERE run_id = ANY($1::uuid[]) GROUP BY run_id
`

type IssueCountsByRunRow struct {
	RunID    uuid.UUID
	Issues   int32
	Accepted int32
	Rejected int32
	Pending  int32
}

func (q *Queries) IssueCountsByRun(ctx context.Context, runIds []uuid.UUID) ([]IssueCountsByRunRow, error) {
	rows, err := q.db.Query(ctx, issueCountsByRun, runIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IssueCountsByRunRow{}
	for rows.Next() {
		var i IssueCountsByRunRow
		if err := rows.Scan(
			&i.RunID,
			&i.Issues,
			&i.Accepted,
			&i.Rejected,
			&i.Pending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChapterHistory = `-- name: ListChapterHistory :many
SELECT id, user_id, project_id, chapter_id, kind, status, trace_id, params, result, error, cost_usd, cost_estimated, prompt_tokens, completion_tokens, created_at, started_at, finished_at FROM runs
WHERE chapter_id = $1 AND user_id = $2
  AND ($3::text = '' OR kind = $3::text)
  AND ($4::timestamptz IS NULL OR created_at < $4::timestamptz)
ORDER BY created_at DESC, id
LIMIT $5
`

type ListChapterHistoryParams struct {
	ChapterID uuid.NullUUID
	UserID    uuid.UUID
	Kind      string
	Before    *time.Time
	RowLimit  int32
}

func (q *Queries) ListChapterHistory(ctx context.Context, arg ListChapterHistoryParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, listChapterHistory,
		arg.ChapterID,
		arg.UserID,
		arg.Kind,
		arg.Before,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.ChapterID,
			&i.Kind,
			&i.Status,
			&i.TraceID,
			&i.Params,
			&i.Result,
			&i.Error,
			&i.CostUsd,
			&i.CostEstimated,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunModelCalls = `-- name: ListRunModelCalls :many
SELECT mc.id, mc.user_id, mc.run_id, mc.writer_id, mc.generation_name, mc.model_alias, mc.prompt_tokens, mc.completion_tokens, mc.cost_usd, mc.cost_estimated, mc.latency_ms, mc.status, mc.error, mc.created_at, w.name AS writer_name
FROM model_calls mc LEFT JOIN writers w ON w.id = mc.writer_id
WHERE mc.run_id = $1 AND mc.user_id = $2
ORDER BY mc.created_at, mc.id
`

type ListRunModelCallsParams struct {
	RunID  uuid.NullUUID
	UserID uuid.UUID
}

type ListRunModelCallsRow struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	RunID            uuid.NullUUID
	WriterID         uuid.NullUUID
	GenerationName   string
	ModelAlias       string
	PromptTokens     int32
	CompletionTokens int32
	CostUsd          float64
	CostEstimated    bool
	LatencyMs        int32
	Status           string
	Error            string
	CreatedAt        time.Time
	WriterName       *string
}

func (q *Queries) ListRunModelCalls(ctx context.Context, arg ListRunModelCallsParams) ([]ListRunModelCallsRow, error) {
	rows, err := q.db.Query(ctx, listRunModelCalls, arg.RunID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunModelCallsRow{}
	for rows.Next() {
		var i ListRunModelCallsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RunID,
			&i.WriterID,
			&i.GenerationName,
			&i.ModelAlias,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.CostUsd,
			&i.CostEstimated,
			&i.LatencyMs,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.WriterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const proposalCountsByRun = `-- name: ProposalCountsByRun :many
SELECT run_id, count(*)::integer AS proposals,
       count(*) FILTER (WHERE status = 'approved')::integer AS approved,
       count(*) FILTER (WHERE status = 'rejected')::integer AS rejected,
       count(*) FILTER (WHERE status = 'pending')::integer AS pending
FROM bible_proposals WHERE run_id = ANY($1::uuid[]) GROUP BY run_id
`

type ProposalCountsByRunRow struct {
	RunID     uuid.UUID
	Proposals int32
	Approved  int32
	Rejected  int32
	Pending   int32
}

func (q *Queries) ProposalCountsByRun(ctx context.Context, runIds []uuid.UUID) ([]ProposalCountsByRunRow, error) {
	rows, err := q.db.Query(ctx, proposalCountsByRun, runIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProposalCountsByRunRow{}
	for rows.Next() {
		var i ProposalCountsByRunRow
		if err := rows.Scan(
			&i.RunID,
			&i.Proposals,
			&i.Approved,
			&i.Rejected,
			&i.Pending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revisionsByRun = `-- name: RevisionsByRun :many
SELECT run_id, status, jsonb_array_length(hunks)::integer AS hunks,
       coalesce(jsonb_array_length(applied_hunks), 0)::integer AS applied_hunks, stats
FROM revisions WHERE run_id = ANY($1::uuid[])
`

type RevisionsByRunRow struct {
	RunID        uuid.UUID
	Status       string
	Hunks        int32
	AppliedHunks int32
	Stats        []byte
}

func (q *Queries) RevisionsByRun(ctx context.Context, runIds []uuid.UUID) ([]RevisionsByRunRow, error) {
	rows, err := q.db.Query(ctx, revisionsByRun, runIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevisionsByRunRow{}
	for rows.Next() {
		var i RevisionsByRunRow
		if err := rows.Scan(
			&i.RunID,
			&i.Status,
			&i.Hunks,
			&i.AppliedHunks,
			&i.Stats,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const writersByRun = `-- name: WritersByRun :many
SELECT mc.run_id, count(*)::integer AS calls, array_remove(array_agg(DISTINCT w.name), NULL)::text[] AS writer_names
FROM model_calls mc LEFT JOIN writers w ON w.id = mc.writer_id
WHERE mc.run_id = ANY($1::uuid[]) GROUP BY mc.run_id
`

type WritersByRunRow struct {
	RunID       uuid.NullUUID
	Calls       int32
	WriterNames []string
}

func (q *Queries) WritersByRun(ctx context.Context, runIds []uuid.UUID) ([]WritersByRunRow, error) {
	rows, err := q.db.Query(ctx, writersByRun, runIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WritersByRunRow{}
	for rows.Next() {
		var i WritersByRunRow
		if err := rows.Scan(&i.RunID, &i.Calls, &i.WriterNames); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
