// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issues.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createIssue = `-- name: CreateIssue :one
INSERT INTO issues (user_id, run_id, chapter_id, position, key, severity, quote, problem, suggested_fix,
                    quote_start, quote_end, quote_exact, sources, content_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, user_id, run_id, chapter_id, position, key, severity, quote, problem, suggested_fix, quote_start, quote_end, quote_exact, sources, decision, edited_fix, decided_at, content_hash, created_at
`

type CreateIssueParams struct {
	UserID       uuid.UUID
	RunID        uuid.UUID
	ChapterID    uuid.NullUUID
	Position     int32
	Key          string
	Severity     string
	Quote        string
	Problem      string
	SuggestedFix string
	QuoteStart   int32
	QuoteEnd     int32
	QuoteExact   bool
	Sources      []byte
	ContentHash  string
}

func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, createIssue,
		arg.UserID,
		arg.RunID,
		arg.ChapterID,
		arg.Position,
		arg.Key,
		arg.Severity,
		arg.Quote,
		arg.Problem,
		arg.SuggestedFix,
		arg.QuoteStart,
		arg.QuoteEnd,
		arg.QuoteExact,
		arg.Sources,
		arg.ContentHash,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RunID,
		&i.ChapterID,
		&i.Position,
		&i.Key,
		&i.Severity,
		&i.Quote,
		&i.Problem,
		&i.SuggestedFix,
		&i.QuoteStart,
		&i.QuoteEnd,
		&i.QuoteExact,
		&i.Sources,
		&i.Decision,
		&i.EditedFix,
		&i.DecidedAt,
		&i.ContentHash,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRunIssues = `-- name: DeleteRunIssues :exec
DELETE FROM issues WHERE run_id = $1 AND user_id = $2
`

type DeleteRunIssuesParams struct {
	RunID  uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteRunIssues(ctx context.Context, arg DeleteRunIssuesParams) error {
	_, err := q.db.Exec(ctx, deleteRunIssues, arg.RunID, arg.UserID)
	return err
}

const getIssue = `-- name: GetIssue :one
SELECT id, user_id, run_id, chapter_id, position, key, severity, quote, problem, suggested_fix, quote_start, quote_end, quote_exact, sources, decision, edited_fix, decided_at, content_hash, created_at FROM issues WHERE id = $1 AND user_id = $2
`

type GetIssueParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetIssue(ctx context.Context, arg GetIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, getIssue, arg.ID, arg.UserID)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RunID,
		&i.ChapterID,
		&i.Position,
		&i.Key,
		&i.Severity,
		&i.Quote,
		&i.Problem,
		&i.SuggestedFix,
		&i.QuoteStart,
		&i.QuoteEnd,
		&i.QuoteExact,
		&i.Sources,
		&i.Decision,
		&i.EditedFix,
		&i.DecidedAt,
		&i.ContentHash,
		&i.CreatedAt,
	)
	return i, err
}

const listRunIssues = `-- name: ListRunIssues :many
SELECT id, user_id, run_id, chapter_id, position, key, severity, quote, problem, suggested_fix, quote_start, quote_end, quote_exact, sources, decision, edited_fix, decided_at, content_hash, created_at FROM issues WHERE run_id = $1 AND user_id = $2 ORDER BY position
`

type ListRunIssuesParams struct {
	RunID  uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) ListRunIssues(ctx context.Context, arg ListRunIssuesParams) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listRunIssues, arg.RunID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RunID,
			&i.ChapterID,
			&i.Position,
			&i.Key,
			&i.Severity,
			&i.Quote,
			&i.Problem,
			&i.SuggestedFix,
			&i.QuoteStart,
			&i.QuoteEnd,
			&i.QuoteExact,
			&i.Sources,
			&i.Decision,
			&i.EditedFix,
			&i.DecidedAt,
			&i.ContentHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
