// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (user_id, name, description) VALUES ($1, $2, $3) RETURNING id, user_id, name, description, created_at, updated_at
`

type CreateProjectParams struct {
	UserID      uuid.UUID
	Name        string
	Description string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.UserID, arg.Name, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects WHERE id = $1 AND user_id = $2
`

type DeleteProjectParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProject, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProject = `-- name: GetProject :one
SELECT id, user_id, name, description, created_at, updated_at FROM projects WHERE id = $1 AND user_id = $2
`

type GetProjectParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, arg.ID, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT p.id, p.user_id, p.name, p.description, p.created_at, p.updated_at, (SELECT count(*) FROM chapters c WHERE c.project_id = p.id)::integer AS chapter_count
FROM projects p
WHERE p.user_id = $1
ORDER BY p.updated_at DESC
`

type ListProjectsRow struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Name         string
	Description  string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	ChapterCount int32
}

func (q *Queries) ListProjects(ctx context.Context, userID uuid.UUID) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsRow{}
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChapterCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchProject = `-- name: TouchProject :exec
UPDATE projects SET updated_at = now() WHERE id = $1
`

func (q *Queries) TouchProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchProject, id)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET name = $3, description = $4, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, description, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Description string
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
