// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: revisions.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const applyRevision = `-- name: ApplyRevision :one
UPDATE revisions SET status = 'applied', applied_hunks = $3, result_hash = $4, decided_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, run_id, chapter_id, critique_run_id, status, base_hash, base_content_md, revised_md, hunks, stats, issue_ids, skipped, applied_hunks, result_hash, created_at, decided_at
`

type ApplyRevisionParams struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	AppliedHunks []byte
	ResultHash   string
}

func (q *Queries) ApplyRevision(ctx context.Context, arg ApplyRevisionParams) (Revision, error) {
	row := q.db.QueryRow(ctx, applyRevision,
		arg.ID,
		arg.UserID,
		arg.AppliedHunks,
		arg.ResultHash,
	)
	var i Revision
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RunID,
		&i.ChapterID,
		&i.CritiqueRunID,
		&i.Status,
		&i.BaseHash,
		&i.BaseContentMd,
		&i.RevisedMd,
		&i.Hunks,
		&i.Stats,
		&i.IssueIds,
		&i.Skipped,
		&i.AppliedHunks,
		&i.ResultHash,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const createRevision = `-- name: CreateRevision :one
INSERT INTO revisions (user_id, run_id, chapter_id, critique_run_id, base_hash, base_content_md, revised_md, hunks, stats, issue_ids, skipped)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, run_id, chapter_id, critique_run_id, status, base_hash, base_content_md, revised_md, hunks, stats, issue_ids, skipped, applied_hunks, result_hash, created_at, decided_at
`

type CreateRevisionParams struct {
	UserID        uuid.UUID
	RunID         uuid.UUID
	ChapterID     uuid.UUID
	CritiqueRunID uuid.NullUUID
	BaseHash      string
	BaseContentMd string
	RevisedMd     string
	Hunks         []byte
	Stats         []byte
	IssueIds      []byte
	Skipped       []byte
}

func (q *Queries) CreateRevision(ctx context.Context, arg CreateRevisionParams) (Revision, error) {
	row := q.db.QueryRow(ctx, createRevision,
		arg.UserID,
		arg.RunID,
		arg.ChapterID,
		arg.CritiqueRunID,
		arg.BaseHash,
		arg.BaseContentMd,
		arg.RevisedMd,
		arg.Hunks,
		arg.Stats,
		arg.IssueIds,
		arg.Skipped,
	)
	var i Revision
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RunID,
		&i.ChapterID,
		&i.CritiqueRunID,
		&i.Status,
		&i.BaseHash,
		&i.BaseContentMd,
		&i.RevisedMd,
		&i.Hunks,
		&i.Stats,
		&i.IssueIds,
		&i.Skipped,
		&i.AppliedHunks,
		&i.ResultHash,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const discardRevision = `-- name: DiscardRevision :one
UPDATE revisions SET status = 'discarded', decided_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, run_id, chapter_id, critique_run_id, status, base_hash, base_content_md, revised_md, hunks, stats, issue_ids, skipped, applied_hunks, result_hash, created_at, decided_at
`

type DiscardRevisionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DiscardRevision(ctx context.Context, arg DiscardRevisionParams) (Revision, error) {
	row := q.db.QueryRow(ctx, discardRevision, arg.ID, arg.UserID)
	var i Revision
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RunID,
		&i.ChapterID,
		&i.CritiqueRunID,
		&i.Status,
		&i.BaseHash,
		&i.BaseContentMd,
		&i.RevisedMd,
		&i.Hunks,
		&i.Stats,
		&i.IssueIds,
		&i.Skipped,
		&i.AppliedHunks,
		&i.ResultHash,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const getRevision = `-- name: GetRevision :one
SELECT id, user_id, run_id, chapter_id, critique_run_id, status, base_hash, base_content_md, revised_md, hunks, stats, issue_ids, skipped, applied_hunks, result_hash, created_at, decided_at FROM revisions WHERE id = $1 AND user_id = $2
`

type GetRevisionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetRevision(ctx context.Context, arg GetRevisionParams) (Revision, error) {
	row := q.db.QueryRow(ctx, getRevision, arg.ID, arg.UserID)
	var i Revision
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RunID,
		&i.ChapterID,
		&i.CritiqueRunID,
		&i.Status,
		&i.BaseHash,
		&i.BaseContentMd,
		&i.RevisedMd,
		&i.Hunks,
		&i.Stats,
		&i.IssueIds,
		&i.Skipped,
		&i.AppliedHunks,
		&i.ResultHash,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const getRevisionByRun = `-- name: GetRevisionByRun :one
SELECT id, user_id, run_id, chapter_id, critique_run_id, status, base_hash, base_content_md, revised_md, hunks, stats, issue_ids, skipped, applied_hunks, result_hash, created_at, decided_at FROM revisions WHERE run_id = $1 AND user_id = $2
`

type GetRevisionByRunParams struct {
	RunID  uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetRevisionByRun(ctx context.Context, arg GetRevisionByRunParams) (Revision, error) {
	row := q.db.QueryRow(ctx, getRevisionByRun, arg.RunID, arg.UserID)
	var i Revision
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RunID,
		&i.ChapterID,
		&i.CritiqueRunID,
		&i.Status,
		&i.BaseHash,
		&i.BaseContentMd,
		&i.RevisedMd,
		&i.Hunks,
		&i.Stats,
		&i.IssueIds,
		&i.Skipped,
		&i.AppliedHunks,
		&i.ResultHash,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const getRevisionForUpdate = `-- name: GetRevisionForUpdate :one
SELECT id, user_id, run_id, chapter_id, critique_run_id, status, base_hash, base_content_md, revised_md, hunks, stats, issue_ids, skipped, applied_hunks, result_hash, created_at, decided_at FROM revisions WHERE id = $1 AND user_id = $2 FOR UPDATE
`

type GetRevisionForUpdateParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetRevisionForUpdate(ctx context.Context, arg GetRevisionForUpdateParams) (Revision, error) {
	row := q.db.QueryRow(ctx, getRevisionForUpdate, arg.ID, arg.UserID)
	var i Revision
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RunID,
		&i.ChapterID,
		&i.CritiqueRunID,
		&i.Status,
		&i.BaseHash,
		&i.BaseContentMd,
		&i.RevisedMd,
		&i.Hunks,
		&i.Stats,
		&i.IssueIds,
		&i.Skipped,
		&i.AppliedHunks,
		&i.ResultHash,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const listChapterRevisions = `-- name: ListChapterRevisions :many
SELECT id, user_id, run_id, chapter_id, critique_run_id, status, base_hash, base_content_md, revised_md, hunks, stats, issue_ids, skipped, applied_hunks, result_hash, created_at, decided_at FROM revisions
WHERE chapter_id = $1 AND user_id = $2 AND ($3::text = '' OR status = $3::text)
ORDER BY created_at DESC
LIMIT $4
`

type ListChapterRevisionsParams struct {
	ChapterID uuid.UUID
	UserID    uuid.UUID
	Status    string
	RowLimit  int32
}

func (q *Queries) ListChapterRevisions(ctx context.Context, arg ListChapterRevisionsParams) ([]Revision, error) {
	rows, err := q.db.Query(ctx, listChapterRevisions,
		arg.ChapterID,
		arg.UserID,
		arg.Status,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Revision{}
	for rows.Next() {
		var i Revision
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RunID,
			&i.ChapterID,
			&i.CritiqueRunID,
			&i.Status,
			&i.BaseHash,
			&i.BaseContentMd,
			&i.RevisedMd,
			&i.Hunks,
			&i.Stats,
			&i.IssueIds,
			&i.Skipped,
			&i.AppliedHunks,
			&i.ResultHash,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
