// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addRunUsage = `-- name: AddRunUsage :exec
UPDATE runs
SET cost_usd = cost_usd + $2,
    cost_estimated = cost_estimated OR $3,
    prompt_tokens = prompt_tokens + $4,
    completion_tokens = completion_tokens + $5
WHERE id = $1
`

type AddRunUsageParams struct {
	ID               uuid.UUID
	CostUsd          float64
	CostEstimated    bool
	PromptTokens     int32
	CompletionTokens int32
}

func (q *Queries) AddRunUsage(ctx context.Context, arg AddRunUsageParams) error {
	_, err := q.db.Exec(ctx, addRunUsage,
		arg.ID,
		arg.CostUsd,
		arg.CostEstimated,
		arg.PromptTokens,
		arg.CompletionTokens,
	)
	return err
}

const appendRunEvent = `-- name: AppendRunEvent :one
INSERT INTO run_events (run_id, seq, type, payload) VALUES ($1, $2, $3, $4) RETURNING run_id, seq, type, payload, created_at
`

type AppendRunEventParams struct {
	RunID   uuid.UUID
	Seq     int32
	Type    string
	Payload []byte
}

func (q *Queries) AppendRunEvent(ctx context.Context, arg AppendRunEventParams) (RunEvent, error) {
	row := q.db.QueryRow(ctx, appendRunEvent,
		arg.RunID,
		arg.Seq,
		arg.Type,
		arg.Payload,
	)
	var i RunEvent
	err := row.Scan(
		&i.RunID,
		&i.Seq,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const createModelCall = `-- name: CreateModelCall :one
INSERT INTO model_calls (user_id, run_id, writer_id, generation_name, model_alias, prompt_tokens, completion_tokens,
                         cost_usd, cost_estimated, latency_ms, status, error)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, user_id, run_id, writer_id, generation_name, model_alias, prompt_tokens, completion_tokens, cost_usd, cost_estimated, latency_ms, status, error, created_at
`

type CreateModelCallParams struct {
	UserID           uuid.UUID
	RunID            uuid.NullUUID
	WriterID         uuid.NullUUID
	GenerationName   string
	ModelAlias       string
	PromptTokens     int32
	CompletionTokens int32
	CostUsd          float64
	CostEstimated    bool
	LatencyMs        int32
	Status           string
	Error            string
}

func (q *Queries) CreateModelCall(ctx context.Context, arg CreateModelCallParams) (ModelCall, error) {
	row := q.db.QueryRow(ctx, createModelCall,
		arg.UserID,
		arg.RunID,
		arg.WriterID,
		arg.GenerationName,
		arg.ModelAlias,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.CostUsd,
		arg.CostEstimated,
		arg.LatencyMs,
		arg.Status,
		arg.Error,
	)
	var i ModelCall
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RunID,
		&i.WriterID,
		&i.GenerationName,
		&i.ModelAlias,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CostUsd,
		&i.CostEstimated,
		&i.LatencyMs,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO runs (id, user_id, project_id, chapter_id, kind, status, trace_id, params, started_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, project_id, chapter_id, kind, status, trace_id, params, result, error, cost_usd, cost_estimated, prompt_tokens, completion_tokens, created_at, started_at, finished_at
`

type CreateRunParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ProjectID uuid.NullUUID
	ChapterID uuid.NullUUID
	Kind      string
	Status    string
	TraceID   string
	Params    []byte
	StartedAt *time.Time
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.ID,
		arg.UserID,
		arg.ProjectID,
		arg.ChapterID,
		arg.Kind,
		arg.Status,
		arg.TraceID,
		arg.Params,
		arg.StartedAt,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.ChapterID,
		&i.Kind,
		&i.Status,
		&i.TraceID,
		&i.Params,
		&i.Result,
		&i.Error,
		&i.CostUsd,
		&i.CostEstimated,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const failStaleRuns = `-- name: FailStaleRuns :execrows
UPDATE runs SET status = 'failed', error = 'interrupted by a server restart', finished_at = now()
WHERE status IN ('queued', 'running')
`

func (q *Queries) FailStaleRuns(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, failStaleRuns)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishRun = `-- name: FinishRun :one
UPDATE runs SET status = $2, result = $3, error = $4, finished_at = now()
WHERE id = $1
RETURNING id, user_id, project_id, chapter_id, kind, status, trace_id, params, result, error, cost_usd, cost_estimated, prompt_tokens, completion_tokens, created_at, started_at, finished_at
`

type FinishRunParams struct {
	ID     uuid.UUID
	Status string
	Result []byte
	Error  string
}

func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, finishRun,
		arg.ID,
		arg.Status,
		arg.Result,
		arg.Error,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.ChapterID,
		&i.Kind,
		&i.Status,
		&i.TraceID,
		&i.Params,
		&i.Result,
		&i.Error,
		&i.CostUsd,
		&i.CostEstimated,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, user_id, project_id, chapter_id, kind, status, trace_id, params, result, error, cost_usd, cost_estimated, prompt_tokens, completion_tokens, created_at, started_at, finished_at FROM runs WHERE id = $1 AND user_id = $2
`

type GetRunParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetRun(ctx context.Context, arg GetRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, getRun, arg.ID, arg.UserID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.ChapterID,
		&i.Kind,
		&i.Status,
		&i.TraceID,
		&i.Params,
		&i.Result,
		&i.Error,
		&i.CostUsd,
		&i.CostEstimated,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listRunEvents = `-- name: ListRunEvents :many
SELECT run_id, seq, type, payload, created_at FROM run_events WHERE run_id = $1 AND seq > $2 ORDER BY seq
`

type ListRunEventsParams struct {
	RunID uuid.UUID
	Seq   int32
}

func (q *Queries) ListRunEvents(ctx context.Context, arg ListRunEventsParams) ([]RunEvent, error) {
	rows, err := q.db.Query(ctx, listRunEvents, arg.RunID, arg.Seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunEvent{}
	for rows.Next() {
		var i RunEvent
		if err := rows.Scan(
			&i.RunID,
			&i.Seq,
			&i.Type,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRunStatus = `-- name: SetRunStatus :one
UPDATE runs SET status = $2, started_at = coalesce(started_at, now()) WHERE id = $1 RETURNING id, user_id, project_id, chapter_id, kind, status, trace_id, params, result, error, cost_usd, cost_estimated, prompt_tokens, completion_tokens, created_at, started_at, finished_at
`

type SetRunStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) SetRunStatus(ctx context.Context, arg SetRunStatusParams) (Run, error) {
	row := q.db.QueryRow(ctx, setRunStatus, arg.ID, arg.Status)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.ChapterID,
		&i.Kind,
		&i.Status,
		&i.TraceID,
		&i.Params,
		&i.Result,
		&i.Error,
		&i.CostUsd,
		&i.CostEstimated,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
