// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const ensureSettings = `-- name: EnsureSettings :exec
INSERT INTO user_settings (user_id) VALUES ($1) ON CONFLICT (user_id) DO NOTHING
`

func (q *Queries) EnsureSettings(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, ensureSettings, userID)
	return err
}

const getSettings = `-- name: GetSettings :one
SELECT user_id, scene_token_limit, autosave_snapshot_minutes, updated_at FROM user_settings WHERE user_id = $1
`

func (q *Queries) GetSettings(ctx context.Context, userID uuid.UUID) (UserSetting, error) {
	row := q.db.QueryRow(ctx, getSettings, userID)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.SceneTokenLimit,
		&i.AutosaveSnapshotMinutes,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSettings = `-- name: UpsertSettings :one
INSERT INTO user_settings (user_id, scene_token_limit, autosave_snapshot_minutes)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE
    SET scene_token_limit = EXCLUDED.scene_token_limit,
        autosave_snapshot_minutes = EXCLUDED.autosave_snapshot_minutes,
        updated_at = now()
RETURNING user_id, scene_token_limit, autosave_snapshot_minutes, updated_at
`

type UpsertSettingsParams struct {
	UserID                  uuid.UUID
	SceneTokenLimit         int32
	AutosaveSnapshotMinutes int32
}

func (q *Queries) UpsertSettings(ctx context.Context, arg UpsertSettingsParams) (UserSetting, error) {
	row := q.db.QueryRow(ctx, upsertSettings, arg.UserID, arg.SceneTokenLimit, arg.AutosaveSnapshotMinutes)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.SceneTokenLimit,
		&i.AutosaveSnapshotMinutes,
		&i.UpdatedAt,
	)
	return i, err
}
