// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const statsCostByWriterKind = `-- name: StatsCostByWriterKind :many
SELECT mc.writer_id, coalesce(r.kind, 'other')::text AS kind, count(*)::integer AS calls,
       coalesce(sum(mc.cost_usd), 0)::double precision AS cost_usd,
       coalesce(bool_or(mc.cost_estimated), false)::boolean AS cost_estimated,
       coalesce(sum(mc.prompt_tokens), 0)::bigint AS prompt_tokens,
       coalesce(sum(mc.completion_tokens), 0)::bigint AS completion_tokens
FROM model_calls mc
LEFT JOIN runs r ON r.id = mc.run_id
WHERE mc.user_id = $1
  AND ($2::timestamptz IS NULL OR mc.created_at >= $2::timestamptz)
  AND ($3::uuid IS NULL OR r.project_id = $3::uuid)
GROUP BY 1, 2
`

type StatsCostByWriterKindParams struct {
	UserID    uuid.UUID
	Since     *time.Time
	ProjectID uuid.NullUUID
}

type StatsCostByWriterKindRow struct {
	WriterID         uuid.NullUUID
	Kind             string
	Calls            int32
	CostUsd          float64
	CostEstimated    bool
	PromptTokens     int64
	CompletionTokens int64
}

func (q *Queries) StatsCostByWriterKind(ctx context.Context, arg StatsCostByWriterKindParams) ([]StatsCostByWriterKindRow, error) {
	rows, err := q.db.Query(ctx, statsCostByWriterKind, arg.UserID, arg.Since, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsCostByWriterKindRow{}
	for rows.Next() {
		var i StatsCostByWriterKindRow
		if err := rows.Scan(
			&i.WriterID,
			&i.Kind,
			&i.Calls,
			&i.CostUsd,
			&i.CostEstimated,
			&i.PromptTokens,
			&i.CompletionTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsCritiquesByWriter = `-- name: StatsCritiquesByWriter :many
SELECT c.writer_id, count(*)::integer AS count
FROM critiques c
JOIN runs r ON r.id = c.run_id
WHERE c.user_id = $1 AND c.status = 'succeeded' AND c.writer_id IS NOT NULL
  AND ($2::timestamptz IS NULL OR c.created_at >= $2::timestamptz)
  AND ($3::uuid IS NULL OR r.project_id = $3::uuid)
GROUP BY c.writer_id
`

type StatsCritiquesByWriterParams struct {
	UserID    uuid.UUID
	Since     *time.Time
	ProjectID uuid.NullUUID
}

type StatsCritiquesByWriterRow struct {
	WriterID uuid.NullUUID
	Count    int32
}

func (q *Queries) StatsCritiquesByWriter(ctx context.Context, arg StatsCritiquesByWriterParams) ([]StatsCritiquesByWriterRow, error) {
	rows, err := q.db.Query(ctx, statsCritiquesByWriter, arg.UserID, arg.Since, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsCritiquesByWriterRow{}
	for rows.Next() {
		var i StatsCritiquesByWriterRow
		if err := rows.Scan(&i.WriterID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsDraftsByWriter = `-- name: StatsDraftsByWriter :many
SELECT d.writer_id, d.decision, count(*)::integer AS count
FROM drafts d
JOIN runs r ON r.id = d.run_id
WHERE d.user_id = $1 AND d.status = 'succeeded' AND d.writer_id IS NOT NULL
  AND ($2::timestamptz IS NULL OR d.created_at >= $2::timestamptz)
  AND ($3::uuid IS NULL OR r.project_id = $3::uuid)
GROUP BY 1, 2
`

type StatsDraftsByWriterParams struct {
	UserID    uuid.UUID
	Since     *time.Time
	ProjectID uuid.NullUUID
}

type StatsDraftsByWriterRow struct {
	WriterID uuid.NullUUID
	Decision string
	Count    int32
}

func (q *Queries) StatsDraftsByWriter(ctx context.Context, arg StatsDraftsByWriterParams) ([]StatsDraftsByWriterRow, error) {
	rows, err := q.db.Query(ctx, statsDraftsByWriter, arg.UserID, arg.Since, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsDraftsByWriterRow{}
	for rows.Next() {
		var i StatsDraftsByWriterRow
		if err := rows.Scan(&i.WriterID, &i.Decision, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsIssuesByWriter = `-- name: StatsIssuesByWriter :many
SELECT (src->>'writer_id')::uuid AS writer_id, i.decision, count(*)::integer AS count
FROM issues i
JOIN runs r ON r.id = i.run_id
CROSS JOIN LATERAL jsonb_array_elements(i.sources) AS src
WHERE i.user_id = $1
  AND ($2::timestamptz IS NULL OR i.created_at >= $2::timestamptz)
  AND ($3::uuid IS NULL OR r.project_id = $3::uuid)
GROUP BY 1, 2
`

type StatsIssuesByWriterParams struct {
	UserID    uuid.UUID
	Since     *time.Time
	ProjectID uuid.NullUUID
}

type StatsIssuesByWriterRow struct {
	WriterID uuid.UUID
	Decision string
	Count    int32
}

func (q *Queries) StatsIssuesByWriter(ctx context.Context, arg StatsIssuesByWriterParams) ([]StatsIssuesByWriterRow, error) {
	rows, err := q.db.Query(ctx, statsIssuesByWriter, arg.UserID, arg.Since, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsIssuesByWriterRow{}
	for rows.Next() {
		var i StatsIssuesByWriterRow
		if err := rows.Scan(&i.WriterID, &i.Decision, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
