// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const usageCallsByUser = `-- name: UsageCallsByUser :many
SELECT user_id, count(*)::integer AS calls,
       coalesce(sum(prompt_tokens), 0)::bigint AS prompt_tokens,
       coalesce(sum(completion_tokens), 0)::bigint AS completion_tokens,
       coalesce(sum(cost_usd), 0)::double precision AS cost_usd,
       coalesce(bool_or(cost_estimated), false)::boolean AS cost_estimated
FROM model_calls
WHERE ($1::timestamptz IS NULL OR created_at >= $1::timestamptz)
GROUP BY user_id
`

type UsageCallsByUserRow struct {
	UserID           uuid.UUID
	Calls            int32
	PromptTokens     int64
	CompletionTokens int64
	CostUsd          float64
	CostEstimated    bool
}

func (q *Queries) UsageCallsByUser(ctx context.Context, since *time.Time) ([]UsageCallsByUserRow, error) {
	rows, err := q.db.Query(ctx, usageCallsByUser, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageCallsByUserRow{}
	for rows.Next() {
		var i UsageCallsByUserRow
		if err := rows.Scan(
			&i.UserID,
			&i.Calls,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.CostUsd,
			&i.CostEstimated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usageHoldingsByUser = `-- name: UsageHoldingsByUser :many
SELECT u.id AS user_id,
       (SELECT count(*) FROM projects p WHERE p.user_id = u.id)::integer AS projects,
       (SELECT count(*) FROM chapters c WHERE c.user_id = u.id)::integer AS chapters
FROM users u
`

type UsageHoldingsByUserRow struct {
	UserID   uuid.UUID
	Projects int32
	Chapters int32
}

func (q *Queries) UsageHoldingsByUser(ctx context.Context) ([]UsageHoldingsByUserRow, error) {
	rows, err := q.db.Query(ctx, usageHoldingsByUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageHoldingsByUserRow{}
	for rows.Next() {
		var i UsageHoldingsByUserRow
		if err := rows.Scan(&i.UserID, &i.Projects, &i.Chapters); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usageRunsByUser = `-- name: UsageRunsByUser :many
SELECT user_id, count(*)::integer AS runs, max(created_at)::timestamptz AS last_run_at
FROM runs
WHERE ($1::timestamptz IS NULL OR created_at >= $1::timestamptz)
GROUP BY user_id
`

type UsageRunsByUserRow struct {
	UserID    uuid.UUID
	Runs      int32
	LastRunAt time.Time
}

func (q *Queries) UsageRunsByUser(ctx context.Context, since *time.Time) ([]UsageRunsByUserRow, error) {
	rows, err := q.db.Query(ctx, usageRunsByUser, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageRunsByUserRow{}
	for rows.Next() {
		var i UsageRunsByUserRow
		if err := rows.Scan(&i.UserID, &i.Runs, &i.LastRunAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
