// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, display_name, password_hash, role)
VALUES ($1, $2, $3, $4)
RETURNING id, username, display_name, password_hash, role, disabled_at, auth_version, created_at, updated_at
`

type CreateUserParams struct {
	Username     string
	DisplayName  string
	PasswordHash string
	Role         string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.DisabledAt,
		&i.AuthVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getFirstUser = `-- name: GetFirstUser :one
SELECT id, username, display_name, password_hash, role, disabled_at, auth_version, created_at, updated_at FROM users ORDER BY created_at ASC LIMIT 1
`

func (q *Queries) GetFirstUser(ctx context.Context) (User, error) {
	row := q.db.QueryRow(ctx, getFirstUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.DisabledAt,
		&i.AuthVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, display_name, password_hash, role, disabled_at, auth_version, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.DisabledAt,
		&i.AuthVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, display_name, password_hash, role, disabled_at, auth_version, created_at, updated_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.DisabledAt,
		&i.AuthVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setUserRole = `-- name: SetUserRole :exec
UPDATE users SET role = $2, updated_at = now() WHERE id = $1
`

type SetUserRoleParams struct {
	ID   uuid.UUID
	Role string
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) error {
	_, err := q.db.Exec(ctx, setUserRole, arg.ID, arg.Role)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, auth_version = auth_version + 1, updated_at = now()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
