// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const cancelRunsByUser = `-- name: CancelRunsByUser :execrows
UPDATE runs SET status = 'cancelled', error = 'the account was disabled', finished_at = now()
WHERE user_id = $1 AND status IN ('queued', 'running')
`

func (q *Queries) CancelRunsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelRunsByUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT count(*) FROM users WHERE role = 'admin' AND disabled_at IS NULL
`

func (q *Queries) CountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, display_name, password_hash, role)
VALUES ($1, $2, $3, $4)
RETURNING id, username, display_name, password_hash, role, disabled_at, auth_version, created_at, updated_at
`

type CreateUserParams struct {
	Username     string
	DisplayName  string
	PasswordHash string
	Role         string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.DisabledAt,
		&i.AuthVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const disableUser = `-- name: DisableUser :one
UPDATE users SET disabled_at = now(), auth_version = auth_version + 1, updated_at = now() WHERE id = $1 RETURNING id, username, display_name, password_hash, role, disabled_at, auth_version, created_at, updated_at
`

func (q *Queries) DisableUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, disableUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.DisabledAt,
		&i.AuthVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enableUser = `-- name: EnableUser :one
UPDATE users SET disabled_at = NULL, updated_at = now() WHERE id = $1 RETURNING id, username, display_name, password_hash, role, disabled_at, auth_version, created_at, updated_at
`

func (q *Queries) EnableUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, enableUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.DisabledAt,
		&i.AuthVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFirstUser = `-- name: GetFirstUser :one
SELECT id, username, display_name, password_hash, role, disabled_at, auth_version, created_at, updated_at FROM users ORDER BY created_at ASC LIMIT 1
`

func (q *Queries) GetFirstUser(ctx context.Context) (User, error) {
	row := q.db.QueryRow(ctx, getFirstUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.DisabledAt,
		&i.AuthVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, display_name, password_hash, role, disabled_at, auth_version, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.DisabledAt,
		&i.AuthVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, display_name, password_hash, role, disabled_at, auth_version, created_at, updated_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.DisabledAt,
		&i.AuthVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserForUpdate = `-- name: GetUserForUpdate :one
SELECT id, username, display_name, password_hash, role, disabled_at, auth_version, created_at, updated_at FROM users WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetUserForUpdate(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserForUpdate, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.DisabledAt,
		&i.AuthVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveRunIDsByUser = `-- name: ListActiveRunIDsByUser :many
SELECT id FROM runs WHERE user_id = $1 AND status IN ('queued', 'running')
`

func (q *Queries) ListActiveRunIDsByUser(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listActiveRunIDsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, display_name, password_hash, role, disabled_at, auth_version, created_at, updated_at FROM users ORDER BY created_at, username
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.PasswordHash,
			&i.Role,
			&i.DisabledAt,
			&i.AuthVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAccounts = `-- name: LockAccounts :exec
SELECT pg_advisory_xact_lock(hashtext('writersguild-accounts'))
`

func (q *Queries) LockAccounts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockAccounts)
	return err
}

const setUserRole = `-- name: SetUserRole :exec
UPDATE users SET role = $2, updated_at = now() WHERE id = $1
`

type SetUserRoleParams struct {
	ID   uuid.UUID
	Role string
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) error {
	_, err := q.db.Exec(ctx, setUserRole, arg.ID, arg.Role)
	return err
}

const updateUserByAdmin = `-- name: UpdateUserByAdmin :one
UPDATE users SET display_name = $2, role = $3, updated_at = now() WHERE id = $1 RETURNING id, username, display_name, password_hash, role, disabled_at, auth_version, created_at, updated_at
`

type UpdateUserByAdminParams struct {
	ID          uuid.UUID
	DisplayName string
	Role        string
}

func (q *Queries) UpdateUserByAdmin(ctx context.Context, arg UpdateUserByAdminParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserByAdmin, arg.ID, arg.DisplayName, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.DisabledAt,
		&i.AuthVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :one
UPDATE users SET display_name = $2, updated_at = now() WHERE id = $1 RETURNING id, username, display_name, password_hash, role, disabled_at, auth_version, created_at, updated_at
`

type UpdateUserDisplayNameParams struct {
	ID          uuid.UUID
	DisplayName string
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserDisplayName, arg.ID, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.DisabledAt,
		&i.AuthVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, auth_version = auth_version + 1, updated_at = now()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
