// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: versions.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createChapterVersion = `-- name: CreateChapterVersion :one
INSERT INTO chapter_versions (user_id, chapter_id, kind, label, content_md, content_hash)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, chapter_id, kind, label, content_md, content_hash, created_at
`

type CreateChapterVersionParams struct {
	UserID      uuid.UUID
	ChapterID   uuid.UUID
	Kind        string
	Label       string
	ContentMd   string
	ContentHash string
}

func (q *Queries) CreateChapterVersion(ctx context.Context, arg CreateChapterVersionParams) (ChapterVersion, error) {
	row := q.db.QueryRow(ctx, createChapterVersion,
		arg.UserID,
		arg.ChapterID,
		arg.Kind,
		arg.Label,
		arg.ContentMd,
		arg.ContentHash,
	)
	var i ChapterVersion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChapterID,
		&i.Kind,
		&i.Label,
		&i.ContentMd,
		&i.ContentHash,
		&i.CreatedAt,
	)
	return i, err
}

const getChapterVersion = `-- name: GetChapterVersion :one
SELECT id, user_id, chapter_id, kind, label, content_md, content_hash, created_at FROM chapter_versions WHERE id = $1 AND user_id = $2
`

type GetChapterVersionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetChapterVersion(ctx context.Context, arg GetChapterVersionParams) (ChapterVersion, error) {
	row := q.db.QueryRow(ctx, getChapterVersion, arg.ID, arg.UserID)
	var i ChapterVersion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChapterID,
		&i.Kind,
		&i.Label,
		&i.ContentMd,
		&i.ContentHash,
		&i.CreatedAt,
	)
	return i, err
}

const latestChapterVersion = `-- name: LatestChapterVersion :one
SELECT id, user_id, chapter_id, kind, label, content_md, content_hash, created_at FROM chapter_versions WHERE chapter_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) LatestChapterVersion(ctx context.Context, chapterID uuid.UUID) (ChapterVersion, error) {
	row := q.db.QueryRow(ctx, latestChapterVersion, chapterID)
	var i ChapterVersion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChapterID,
		&i.Kind,
		&i.Label,
		&i.ContentMd,
		&i.ContentHash,
		&i.CreatedAt,
	)
	return i, err
}

const listChapterVersions = `-- name: ListChapterVersions :many
SELECT id, user_id, chapter_id, kind, label, content_hash, created_at,
       length(content_md)::integer AS content_length
FROM chapter_versions
WHERE chapter_id = $1 AND user_id = $2
ORDER BY created_at DESC, id
`

type ListChapterVersionsParams struct {
	ChapterID uuid.UUID
	UserID    uuid.UUID
}

type ListChapterVersionsRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	ChapterID     uuid.UUID
	Kind          string
	Label         string
	ContentHash   string
	CreatedAt     time.Time
	ContentLength int32
}

func (q *Queries) ListChapterVersions(ctx context.Context, arg ListChapterVersionsParams) ([]ListChapterVersionsRow, error) {
	rows, err := q.db.Query(ctx, listChapterVersions, arg.ChapterID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChapterVersionsRow{}
	for rows.Next() {
		var i ListChapterVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChapterID,
			&i.Kind,
			&i.Label,
			&i.ContentHash,
			&i.CreatedAt,
			&i.ContentLength,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
