// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: writers.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createWriter = `-- name: CreateWriter :one
INSERT INTO writers (user_id, name, slug, model_alias, system_prompt, roles, enabled, temperature, is_system)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, name, slug, model_alias, system_prompt, roles, enabled, temperature, is_system, created_at, updated_at
`

type CreateWriterParams struct {
	UserID       uuid.UUID
	Name         string
	Slug         string
	ModelAlias   string
	SystemPrompt string
	Roles        []string
	Enabled      bool
	Temperature  float64
	IsSystem     bool
}

func (q *Queries) CreateWriter(ctx context.Context, arg CreateWriterParams) (Writer, error) {
	row := q.db.QueryRow(ctx, createWriter,
		arg.UserID,
		arg.Name,
		arg.Slug,
		arg.ModelAlias,
		arg.SystemPrompt,
		arg.Roles,
		arg.Enabled,
		arg.Temperature,
		arg.IsSystem,
	)
	var i Writer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.ModelAlias,
		&i.SystemPrompt,
		&i.Roles,
		&i.Enabled,
		&i.Temperature,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWriter = `-- name: DeleteWriter :execrows
DELETE FROM writers WHERE id = $1 AND user_id = $2 AND is_system = false
`

type DeleteWriterParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteWriter(ctx context.Context, arg DeleteWriterParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWriter, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWriter = `-- name: GetWriter :one
SELECT id, user_id, name, slug, model_alias, system_prompt, roles, enabled, temperature, is_system, created_at, updated_at FROM writers WHERE id = $1 AND user_id = $2
`

type GetWriterParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetWriter(ctx context.Context, arg GetWriterParams) (Writer, error) {
	row := q.db.QueryRow(ctx, getWriter, arg.ID, arg.UserID)
	var i Writer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.ModelAlias,
		&i.SystemPrompt,
		&i.Roles,
		&i.Enabled,
		&i.Temperature,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWriterBySlug = `-- name: GetWriterBySlug :one
SELECT id, user_id, name, slug, model_alias, system_prompt, roles, enabled, temperature, is_system, created_at, updated_at FROM writers WHERE user_id = $1 AND slug = $2
`

type GetWriterBySlugParams struct {
	UserID uuid.UUID
	Slug   string
}

func (q *Queries) GetWriterBySlug(ctx context.Context, arg GetWriterBySlugParams) (Writer, error) {
	row := q.db.QueryRow(ctx, getWriterBySlug, arg.UserID, arg.Slug)
	var i Writer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.ModelAlias,
		&i.SystemPrompt,
		&i.Roles,
		&i.Enabled,
		&i.Temperature,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWriterSlugs = `-- name: ListWriterSlugs :many
SELECT slug FROM writers WHERE user_id = $1
`

func (q *Queries) ListWriterSlugs(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listWriterSlugs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWriters = `-- name: ListWriters :many
SELECT id, user_id, name, slug, model_alias, system_prompt, roles, enabled, temperature, is_system, created_at, updated_at FROM writers WHERE user_id = $1 ORDER BY is_system, lower(name)
`

func (q *Queries) ListWriters(ctx context.Context, userID uuid.UUID) ([]Writer, error) {
	rows, err := q.db.Query(ctx, listWriters, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Writer{}
	for rows.Next() {
		var i Writer
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Slug,
			&i.ModelAlias,
			&i.SystemPrompt,
			&i.Roles,
			&i.Enabled,
			&i.Temperature,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWriter = `-- name: UpdateWriter :one
UPDATE writers
SET name = $3, model_alias = $4, system_prompt = $5, roles = $6, enabled = $7, temperature = $8, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, slug, model_alias, system_prompt, roles, enabled, temperature, is_system, created_at, updated_at
`

type UpdateWriterParams struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Name         string
	ModelAlias   string
	SystemPrompt string
	Roles        []string
	Enabled      bool
	Temperature  float64
}

func (q *Queries) UpdateWriter(ctx context.Context, arg UpdateWriterParams) (Writer, error) {
	row := q.db.QueryRow(ctx, updateWriter,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.ModelAlias,
		arg.SystemPrompt,
		arg.Roles,
		arg.Enabled,
		arg.Temperature,
	)
	var i Writer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.ModelAlias,
		&i.SystemPrompt,
		&i.Roles,
		&i.Enabled,
		&i.Temperature,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
